import React, { useCallback, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Check, ClipboardCheck, X } from 'lucide-react-native';
import { useAuth, useTheme } from '@invoice-monorepo/hooks';
import { resolveWorkspace, supabase } from '@invoice-monorepo/api';
import { listHrApprovals, resolveHrApproval, subscribeToHrChanges, type HrApproval } from '@invoice-monorepo/hr';

const BLUE = '#004FFE';

export function ApprovalsScreen({ navigation }: any) {
  const { user } = useAuth();
  const { isDark } = useTheme();
  const [approvals, setApprovals] = useState<HrApproval[]>([]);
  const [refreshing, setRefreshing] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);
  const colors = { bg: isDark ? '#0f172a' : '#f7f9fc', card: isDark ? '#1e293b' : '#fff', text: isDark ? '#fff' : '#12213f', muted: isDark ? '#94a3b8' : '#6f7d96', border: isDark ? '#334155' : '#e4e9f0' };
  const load = useCallback(async () => { if (!user) return; setRefreshing(true); try { const workspace = await resolveWorkspace(supabase, user.id); setApprovals(await listHrApprovals(supabase, workspace.companyId)); } catch (error) { console.warn('Unable to load HR approvals', error); } finally { setRefreshing(false); } }, [user]);
  useFocusEffect(useCallback(() => { void load(); let remove: (() => void) | undefined; void (async () => { if (!user) return; try { const workspace = await resolveWorkspace(supabase, user.id); remove = subscribeToHrChanges(supabase, workspace.companyId, () => { void load(); }); } catch { /* The focused screen still has a manual refresh fallback. */ } })(); return () => remove?.(); }, [load, user]));
  async function resolve(approval: HrApproval, status: 'approved' | 'rejected') { if (approval.resource_type === 'leave_request') { navigation.navigate('Leave'); return; } setBusyId(approval.id); try { await resolveHrApproval(supabase, approval.id, status); await load(); } catch (error) { console.warn('Unable to resolve HR approval', error); } finally { setBusyId(null); } }
  return <View style={[styles.container, { backgroundColor: colors.bg }]}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}><X color={colors.muted} size={20} /></TouchableOpacity><View><Text style={[styles.kicker, { color: BLUE }]}>OPERIX HR</Text><Text style={[styles.title, { color: colors.text }]}>Approvals</Text></View><View style={styles.headerIcon}><ClipboardCheck color={BLUE} size={19} /></View></View><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load()} tintColor={BLUE} />}>{approvals.length ? approvals.map((approval) => <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]} key={approval.id}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={[styles.resource, { color: colors.text }]}>{approval.resource_type.replace(/_/g, ' ')}</Text><Text style={[styles.meta, { color: colors.muted }]}>{approval.status} · {approval.created_at ? new Date(approval.created_at).toLocaleDateString() : 'No date'}</Text></View><View style={[styles.status, { backgroundColor: approval.status === 'pending' ? '#fff7e7' : approval.status === 'approved' ? '#eaf8f2' : '#fff0f2' }]}><Text style={{ color: approval.status === 'pending' ? '#b97709' : approval.status === 'approved' ? '#138a62' : '#c43d53', fontSize: 10, fontWeight: '800' }}>{approval.status}</Text></View></View>{approval.note ? <Text style={[styles.note, { color: colors.muted }]}>{approval.note}</Text> : null}{approval.status === 'pending' ? <View style={styles.actions}><TouchableOpacity onPress={() => void resolve(approval, 'rejected')} disabled={busyId === approval.id} style={[styles.action, { backgroundColor: '#fff0f2' }]}><X color="#c43d53" size={15} /><Text style={{ color: '#c43d53', fontSize: 11, fontWeight: '800' }}>{approval.resource_type === 'leave_request' ? 'Review' : 'Reject'}</Text></TouchableOpacity><TouchableOpacity onPress={() => void resolve(approval, 'approved')} disabled={busyId === approval.id} style={[styles.action, { backgroundColor: '#eaf8f2' }]}><Check color="#138a62" size={15} /><Text style={{ color: '#138a62', fontSize: 11, fontWeight: '800' }}>{approval.resource_type === 'leave_request' ? 'Open leave' : 'Approve'}</Text></TouchableOpacity></View> : null}</View>) : <View style={styles.empty}><ClipboardCheck color={BLUE} size={24} /><Text style={[styles.emptyTitle, { color: colors.text }]}>No pending approvals</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Leave and other HR approval work will appear here.</Text></View>}</ScrollView></View>;
}

const styles = StyleSheet.create({ container: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 56, paddingBottom: 12 }, back: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, kicker: { fontSize: 9, fontWeight: '800', letterSpacing: 1.4, textAlign: 'center' }, title: { marginTop: 3, fontSize: 19, fontWeight: '800' }, headerIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: '#eef3ff' }, content: { padding: 16, paddingBottom: 35 }, card: { marginBottom: 10, padding: 14, borderWidth: 1, borderRadius: 14 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, resource: { fontSize: 13, fontWeight: '800', textTransform: 'capitalize' }, meta: { marginTop: 3, fontSize: 10, textTransform: 'capitalize' }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, note: { marginTop: 10, fontSize: 11, lineHeight: 16 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 12 }, action: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8 }, empty: { alignItems: 'center', paddingTop: 70 }, emptyTitle: { marginTop: 12, fontSize: 14, fontWeight: '800' }, emptyText: { maxWidth: 260, marginTop: 5, textAlign: 'center', fontSize: 11 } });
