import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { InvoiceDocument, type DocumentCompany } from "@/components/invoice-document";
import { PortalPrintButton } from "@/components/portal-print-button";
import type { InvoiceDraft } from "@/lib/models";

export default async function PortalInvoicePrintPage({ params, searchParams }: { params: Promise<{ token:string; invoiceId:string }>; searchParams: Promise<{lang?:string}> }) {
 const {token,invoiceId}=await params; const {lang}=await searchParams; const al=lang==="al"; const supabase=await createClient(); const result=supabase?await supabase.rpc("get_customer_portal_data",{portal_token:token}):{data:null,error:{message:"Portal service is not configured."}}; const data=(result.data||{}) as {error?:string;company?:{company_name?:string;name?:string;email?:string;website?:string;phone?:string;address?:string;city?:string;country?:string;tax_id?:string;bank_name?:string;bank_iban?:string};client?:{id?:string;name?:string;email?:string;phone?:string;address?:string;city?:string;country?:string;tax_id?:string};invoices?:Array<{id:string;invoice_number:string;issue_date:string;due_date?:string;status:string;total_amount:number;amount_received?:number;tax_amount?:number;notes?:string;items:Array<{id?:string;description:string;quantity:number;unit_price:number;tax_rate?:number;discount?:number;unit?:string;amount:number}>}>}; const invoice=data.invoices?.find(item=>item.id===invoiceId);
 if(result.error||data.error||!invoice)return <main className="min-h-screen bg-[#f7f9fc] p-8"><section className="card mx-auto max-w-lg p-8 text-center"><img src="/operix-logo-blue.svg" alt="OperiX" className="mx-auto h-10 w-auto"/><h1 className="mt-6 text-xl font-semibold">{al?"Fatura nuk është e disponueshme":"Invoice unavailable"}</h1><p className="muted mt-2 text-sm">{data.error||result.error?.message||"This invoice is no longer available."}</p><Link href={`/portal/${token}?lang=${al?"al":"en"}`} className="btn btn-primary mt-6">{al?"Kthehu te portali":"Back to portal"}</Link></section></main>;
 const company=data.company||{}; const documentCompany:DocumentCompany={name:company.company_name||company.name||"OperiX Invoice",email:company.email||"",phone:company.phone||"",address:company.address||"",city:[company.city,company.country].filter(Boolean).join(", "),taxId:company.tax_id||"",bankName:company.bank_name||"",iban:company.bank_iban||"",website:company.website||""}; const draft:InvoiceDraft={client_id:data.client?.id||"",invoice_number:invoice.invoice_number,issue_date:invoice.issue_date,due_date:invoice.due_date||invoice.issue_date,payment_method:"bank",amount_received:Number(invoice.amount_received||0),notes:invoice.notes||"",status:invoice.status as InvoiceDraft["status"],items:(invoice.items||[]).map((item,index)=>({id:item.id||String(index),description:item.description,quantity:Number(item.quantity||0),unit_price:Number(item.unit_price||0),tax_rate:Number(item.tax_rate||0),discount:Number(item.discount||0),unit:item.unit||"pcs"}))};
 const client={...(data.client||{}),created_at:""} as never;
 return <main className="min-h-screen bg-[#eef3f8] p-4 sm:p-8 print:bg-white print:p-0"><div className="no-print mx-auto mb-5 flex max-w-[820px] items-center justify-between"><Link href={`/portal/${token}?lang=${al?"al":"en"}`} className="btn">← {al?"Kthehu te portali":"Back to portal"}</Link><div className="flex gap-2"><Link href={`/portal/${token}/invoice/${invoice.id}?lang=${al?"en":"al"}`} className="btn">{al?"EN":"AL"}</Link><PortalPrintButton/></div></div><article className="mx-auto max-w-[820px] bg-white p-3 shadow-xl sm:p-6 print:shadow-none"><InvoiceDocument draft={draft} client={client} company={documentCompany} template="corporate" config={{style:"corporate",pageSize:"A4",showSignature:true,showBuyerSignature:true,showStamp:true,showNotes:true,showDiscount:true,showTax:true,showBankDetails:true,labels:al?{invoice:"FATURË",billTo:"FATURUAR PËR",date:"DATA",due:"AFATI",subtotal:"NËNTOTAL",discount:"ZBRITJE",tax:"TVSH",total:"TOTALI",totalDue:"PËR T’U PAGUAR"}:undefined}}/></article></main>;
}
