import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { money, shortDate } from "@/lib/format";
import { PortalPrintButton } from "@/components/portal-print-button";

export default async function PortalInvoicePrintPage({ params }: { params: Promise<{ token:string; invoiceId:string }> }) {
  const { token, invoiceId } = await params; const supabase=await createClient(); const result=supabase?await supabase.rpc("get_customer_portal_data",{portal_token:token}):{data:null,error:{message:"Portal service is not configured."}}; const data=(result.data||{}) as {error?:string;company?:{company_name?:string;name?:string;email?:string;website?:string};client?:{name?:string;email?:string;address?:string;city?:string;country?:string};invoices?:Array<{id:string;invoice_number:string;issue_date:string;due_date?:string;status:string;total_amount:number;tax_amount?:number;notes?:string;items:Array<{description:string;quantity:number;unit_price:number;amount:number}>}>}; const invoice=data.invoices?.find(item=>item.id===invoiceId);
  if(result.error||data.error||!invoice)return <main className="min-h-screen bg-[#f7f9fc] p-8"><section className="card mx-auto max-w-lg p-8 text-center"><img src="/operix-logo-blue.svg" alt="OperiX" className="mx-auto h-10 w-auto"/><h1 className="mt-6 text-xl font-semibold">Invoice unavailable</h1><p className="muted mt-2 text-sm">{data.error||result.error?.message||"This invoice is no longer available."}</p><Link href={`/portal/${token}`} className="btn btn-primary mt-6">Back to portal</Link></section></main>;
  const companyName=data.company?.company_name||data.company?.name||"OperiX Invoice";
  return <main className="min-h-screen bg-[#eef3f8] p-4 sm:p-8 print:bg-white print:p-0"><div className="no-print mx-auto mb-5 flex max-w-[820px] items-center justify-between"><Link href={`/portal/${token}`} className="btn">← Back to portal</Link><PortalPrintButton/></div><article className="mx-auto min-h-[297mm] max-w-[820px] bg-white p-8 shadow-xl sm:p-14 print:shadow-none"><header className="flex items-start justify-between border-b-2 border-[#101828] pb-7"><div><img src="/operix-logo-blue.svg" alt="OperiX" className="h-12 w-auto"/><p className="mt-3 text-xs text-[#667085]">{data.company?.email||data.company?.website||""}</p></div><div className="text-right"><p className="text-xs uppercase tracking-wide text-[#667085]">Invoice</p><h1 className="mt-1 text-2xl font-bold">{invoice.invoice_number}</h1><p className="mt-2 text-xs text-[#667085]">Issued {shortDate(invoice.issue_date)}<br/>Due {shortDate(invoice.due_date)}</p></div></header><section className="mt-8"><p className="text-xs font-semibold uppercase tracking-wide text-[#667085]">Bill to</p><h2 className="mt-2 text-lg font-semibold">{data.client?.name||"Customer"}</h2><p className="mt-1 text-sm text-[#667085]">{[data.client?.email,data.client?.address,data.client?.city,data.client?.country].filter(Boolean).join(" · ")}</p></section><table className="mt-10 w-full border-collapse text-sm"><thead><tr className="border-b-2 border-[#101828] text-left"><th className="pb-3">Description</th><th className="pb-3 text-right">Qty</th><th className="pb-3 text-right">Unit price</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{invoice.items.map((item,index)=><tr className="border-b border-[#e4e9f0]" key={index}><td className="py-4">{item.description}</td><td className="py-4 text-right">{item.quantity}</td><td className="py-4 text-right">{money(item.unit_price)}</td><td className="py-4 text-right font-medium">{money(item.amount)}</td></tr>)}</tbody></table><div className="ml-auto mt-8 max-w-xs border-t-2 border-[#101828] pt-4"><div className="flex justify-between text-xl font-bold"><span>Total</span><span>{money(invoice.total_amount)}</span></div></div>{invoice.notes&&<p className="mt-10 border-t border-[#e4e9f0] pt-5 text-sm text-[#667085]">{invoice.notes}</p>}<footer className="mt-24 border-t border-[#e4e9f0] pt-4 text-xs text-[#667085]">Thank you for your business · Powered by OperiX Suite</footer></article></main>;
}
