import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { money, shortDate } from "@/lib/format";

type PortalInvoice = { id:string; invoice_number:string; issue_date:string; due_date?:string; status:string; total_amount:number; amount_received?:number; tax_amount?:number; notes?:string; items:Array<{description:string;quantity:number;unit_price:number;amount:number}> };
type PortalData = { error?:string; company?:{company_name?:string;name?:string;website?:string;email?:string;phone?:string}; client?:{name?:string;email?:string;address?:string;city?:string;country?:string;tax_id?:string}; invoices?:PortalInvoice[] };

export default async function CustomerPortalPage({ params }: { params: Promise<{ token:string }> }) {
  const { token } = await params;
  const supabase = await createClient();
  const result = supabase ? await supabase.rpc("get_customer_portal_data", { portal_token: token }) : { data:null, error:{ message:"Portal service is not configured." } };
  const data = (result.data || {}) as PortalData;
  if (result.error || data.error) return <main className="min-h-screen bg-[#f7f9fc] px-4 py-16"><section className="card mx-auto max-w-lg p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-[#edf4ff] text-[#004ffe]">OX</div><h1 className="mt-5 text-xl font-semibold">Customer portal unavailable</h1><p className="muted mt-2 text-sm">{data.error || result.error?.message}</p><Link href="/login" className="btn btn-primary mt-6">Open OperiX Invoice</Link></section></main>;
  const companyName = data.company?.company_name || data.company?.name || "OperiX Invoice";
  return <main className="min-h-screen bg-[#f7f9fc] px-4 py-8 sm:py-12"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-wrap items-center gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#004ffe]">OperiX customer portal</p><h1 className="mt-2 text-2xl font-semibold text-[#101828]">{companyName}</h1></div><span className="ml-auto rounded-full border border-[#dbe5f5] bg-white px-3 py-1.5 text-xs text-[#667085]">Secure shared view</span></header><section className="card mb-5 p-5 sm:p-6"><p className="text-xs uppercase tracking-wide text-[#98a2b3]">Billed to</p><h2 className="mt-1 text-lg font-semibold">{data.client?.name || "Customer"}</h2><p className="muted mt-1 text-sm">{[data.client?.email,data.client?.address,data.client?.city,data.client?.country].filter(Boolean).join(" · ")}</p></section><section className="grid gap-5">{(data.invoices || []).map(invoice=><article className="card overflow-hidden" key={invoice.id}><header className="flex flex-wrap items-start gap-3 border-b border-[#edf0f4] p-5"><div><p className="text-xs text-[#98a2b3]">Invoice</p><h2 className="mt-1 font-semibold text-[#101828]">{invoice.invoice_number}</h2><p className="muted mt-1 text-xs">Issued {shortDate(invoice.issue_date)} · Due {shortDate(invoice.due_date)}</p></div><div className="ml-auto text-right"><span className="status status-{invoice.status}">{invoice.status}</span><strong className="mt-2 block text-lg">{money(invoice.total_amount)}</strong></div></header><div className="overflow-x-auto p-5"><table className="data-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{(invoice.items || []).map((item,index)=><tr key={`${invoice.id}-${index}`}><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unit_price)}</td><td>{money(item.amount)}</td></tr>)}</tbody></table>{invoice.notes&&<p className="muted mt-4 text-xs">{invoice.notes}</p>}</div></article>)}{!(data.invoices || []).length&&<section className="card p-10 text-center"><h2 className="font-semibold">No invoices yet</h2><p className="muted mt-2 text-sm">Your company will publish invoices here when they are ready.</p></section>}</section><footer className="muted mt-8 text-center text-xs">Powered by <Link href="https://operixsuite.com" className="text-[#004ffe]">OperiX Suite</Link></footer></div></main>;
}
