import type { CategoryDefinition, ProductDefinition, ProductKey } from "./types";

const category = (name: string, order: number, description?: string): CategoryDefinition => ({
  slug: name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  name,
  order,
  description,
});

export const productDefinitions: ProductDefinition[] = [
  {
    key: "suite",
    name: "OperiX Suite",
    description: "Learn how accounts, organizations and applications work together.",
    icon: "layout-grid",
    categories: [
      "Getting Started",
      "OperiX Account",
      "Organizations",
      "Organization Switching",
      "Application Switching",
      "Users",
      "Roles",
      "Permissions",
      "Notifications",
      "Profile",
      "Localization",
      "Security",
      "MFA",
      "Sessions",
      "Mobile Apps",
      "OperiX Control",
    ].map((name, index) => category(name, index)),
  },
  {
    key: "control",
    name: "OperiX Control",
    description: "Manage your organization, users, applications and security.",
    icon: "sliders",
    categories: [
      "Getting Started",
      "Overview",
      "Organization",
      "Users",
      "Teams",
      "Roles & Permissions",
      "Applications",
      "Integrations",
      "Billing",
      "Usage",
      "Security",
      "Audit Log",
      "API & Webhooks",
      "Data & Storage",
      "Settings",
    ].map((name, index) => category(name, index)),
  },
  {
    key: "invoice",
    name: "OperiX Invoice",
    description: "Create invoices, manage payments, customers, accounting and reports.",
    icon: "receipt",
    categories: [
      "Getting Started",
      "Dashboard",
      "Customers",
      "Products & Services",
      "Invoices",
      "Quotes",
      "Proforma Invoices",
      "Delivery Notes",
      "Orders",
      "Payments",
      "Expenses",
      "Inventory",
      "POS",
      "Accounting",
      "Reports",
      "Documents",
      "Settings",
      "Integrations",
      "Mobile App",
      "Troubleshooting",
    ].map((name, index) => category(name, index)),
  },
  {
    key: "hr",
    name: "OperiX HR",
    description: "Manage employees, attendance, leave, payroll and recruitment.",
    icon: "users",
    categories: [
      "Getting Started",
      "Dashboard",
      "Employees",
      "Departments",
      "Attendance",
      "Leave",
      "Payroll",
      "Recruitment",
      "Performance",
      "Documents",
      "Contracts",
      "Onboarding",
      "Offboarding",
      "Reports",
      "Mobile App",
      "Settings",
      "Troubleshooting",
    ].map((name, index) => category(name, index)),
  },
  {
    key: "booking",
    name: "OperiX Booking",
    description: "Manage appointments, services, customers and reservations.",
    icon: "calendar",
    categories: [
      "Getting Started",
      "Dashboard",
      "Bookings",
      "Calendar",
      "Customers",
      "Services",
      "Staff",
      "Resources",
      "Locations",
      "Availability",
      "Payments",
      "Public Booking Page",
      "Notifications",
      "Reports",
      "Mobile App",
      "Settings",
      "Troubleshooting",
    ].map((name, index) => category(name, index)),
  },
  {
    key: "desk",
    name: "OperiX Desk",
    description: "Manage desk reservations, floors, teams and workplaces.",
    icon: "building",
    categories: [
      "Getting Started",
      "Dashboard",
      "Reserving a Desk",
      "Floor Plan",
      "My Reservations",
      "Teams",
      "Finding Colleagues",
      "Resources",
      "Workspace Management",
      "Floor Builder",
      "Analytics",
      "Mobile App",
      "Settings",
      "Troubleshooting",
    ].map((name, index) => category(name, index)),
  },
];

export const productsByKey = Object.fromEntries(productDefinitions.map((product) => [product.key, product])) as Record<ProductKey, ProductDefinition>;

export function getProduct(key: string): ProductDefinition | undefined {
  return productDefinitions.find((product) => product.key === key);
}

export function getCategory(product: ProductDefinition, slug: string) {
  return product.categories.find((item) => item.slug === slug);
}
