import type { Locale } from "./types";

export const uiCopy: Record<Locale, Record<string, string>> = {
  en: {
    helpCenter: "Help Center",
    documentation: "Documentation",
    api: "API",
    whatsNew: "What's New",
    support: "Support",
    howCanWeHelp: "How can we help?",
    heroDescription: "Search guides, documentation and answers across OperiX.",
    searchDocumentation: "Search documentation...",
    popular: "Popular:",
    browseByProduct: "Browse by Product",
    gettingStarted: "Getting Started",
    popularGuides: "Popular Guides",
    faq: "Frequently Asked Questions",
    developers: "For Developers",
    troubleshooting: "Troubleshooting",
    stillNeedHelp: "Still Need Help?",
    whatsNewDescription: "Stay up to date with the latest OperiX product information.",
    contactSupport: "Contact Support",
    viewDocumentation: "View Documentation",
    viewAll: "View all",
    comingSoon: "Documentation coming soon.",
    comingSoonDescription: "We're currently preparing guides for this section.",
    onThisPage: "On this page",
    lastUpdated: "Last updated",
    read: "read",
    relatedArticles: "Related Articles",
    previous: "Previous",
    next: "Next",
    wasHelpful: "Was this article helpful?",
    yes: "Yes",
    no: "No",
    noSearchResults: "No results for",
    tryDifferentSearch: "Try a different search or browse by product.",
    searchResultsFor: "Search results for",
    result: "result",
    results: "results",
    breadcrumbHome: "Help Center",
    english: "English",
    albanian: "Shqip",
  },
  sq: {
    helpCenter: "Qendra e Ndihmës",
    documentation: "Dokumentacioni",
    api: "API",
    whatsNew: "Çfarë ka të re",
    support: "Mbështetje",
    howCanWeHelp: "Si mund t'ju ndihmojmë?",
    heroDescription: "Kërkoni udhëzime, dokumentacion dhe përgjigje për OperiX.",
    searchDocumentation: "Kërko në dokumentacion...",
    popular: "Popullore:",
    browseByProduct: "Shfleto sipas produktit",
    gettingStarted: "Fillimi",
    popularGuides: "Udhëzime popullore",
    faq: "Pyetje të shpeshta",
    developers: "Për zhvilluesit",
    troubleshooting: "Zgjidhja e problemeve",
    stillNeedHelp: "Keni ende nevojë për ndihmë?",
    whatsNewDescription: "Qëndroni të informuar për përditësimet e OperiX.",
    contactSupport: "Kontakto mbështetjen",
    viewDocumentation: "Shiko dokumentacionin",
    viewAll: "Shiko të gjitha",
    comingSoon: "Dokumentacioni së shpejti.",
    comingSoonDescription: "Po përgatisim udhëzimet për këtë seksion.",
    onThisPage: "Në këtë faqe",
    lastUpdated: "Përditësuar më",
    read: "lexim",
    relatedArticles: "Artikuj të ngjashëm",
    previous: "E mëparshme",
    next: "Tjetra",
    wasHelpful: "A ishte i dobishëm ky artikull?",
    yes: "Po",
    no: "Jo",
    noSearchResults: "Nuk ka rezultate për",
    tryDifferentSearch: "Provoni një kërkim tjetër ose shfletoni sipas produktit.",
    searchResultsFor: "Rezultatet e kërkimit për",
    result: "rezultat",
    results: "rezultate",
    breadcrumbHome: "Qendra e Ndihmës",
    english: "English",
    albanian: "Shqip",
  },
};

export function copy(locale: Locale, key: string) {
  return uiCopy[locale][key] ?? uiCopy.en[key] ?? key;
}
