import React, { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { ChevronLeft, FileLock } from 'lucide-react-native';
import { useTheme } from '@invoice-monorepo/hooks';
import { Button, Card, LoadingOverlay } from '@invoice-monorepo/ui';
import { resolveWorkspace, supabase } from '@invoice-monorepo/api';
import { employeeSchema } from '@invoice-monorepo/hr';

export function EmployeeFormScreen({ navigation, route }: any) {
  const { isDark } = useTheme();
  const [loading, setLoading] = useState(Boolean(route.params?.id));
  const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [jobTitle, setJobTitle] = useState(''); const [department, setDepartment] = useState(''); const [employeeNumber, setEmployeeNumber] = useState(''); const [hireDate, setHireDate] = useState(new Date().toISOString().slice(0, 10)); const [status, setStatus] = useState<'active' | 'onboarding' | 'on_leave' | 'terminated' | 'pending'>('active');
  const editingId = route.params?.id as string | undefined;
  const colors = { bg: isDark ? '#0f172a' : '#f7f9fc', card: isDark ? '#1e293b' : '#fff', text: isDark ? '#fff' : '#12213f', muted: isDark ? '#94a3b8' : '#6f7d96', border: isDark ? '#334155' : '#e4e9f0' };
  useEffect(() => { if (!editingId) return; void (async () => { const { data, error } = await supabase.from('employees').select('id,company_id,first_name,last_name,email,phone,job_title,department,status,hire_date,employee_number').eq('id', editingId).single(); if (error) Alert.alert('Unable to load employee', error.message); if (data) { setFirstName(data.first_name); setLastName(data.last_name); setEmail(data.email || ''); setPhone(data.phone || ''); setJobTitle(data.job_title || ''); setDepartment(data.department || ''); setStatus(data.status || 'active'); setHireDate(data.hire_date || new Date().toISOString().slice(0, 10)); setEmployeeNumber(data.employee_number || ''); } setLoading(false); })(); }, [editingId]);
  async function save() { const parsed = employeeSchema.safeParse({ first_name: firstName, last_name: lastName, email, phone, job_title: jobTitle, department, employee_number: employeeNumber, hire_date: hireDate, status }); if (!parsed.success) { Alert.alert('Check employee details', parsed.error.issues[0]?.message || 'First and last name are required.'); return; } setLoading(true); try { const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Not authenticated'); const workspace = await resolveWorkspace(supabase, user.id); const payload = { ...parsed.data, company_id: workspace.companyId, email: parsed.data.email || null, phone: parsed.data.phone || null, job_title: parsed.data.job_title || null, department: parsed.data.department || null, employee_number: parsed.data.employee_number || null, hire_date: parsed.data.hire_date || null }; const result = editingId ? await supabase.from('employees').update(payload).eq('id', editingId).eq('company_id', workspace.companyId) : await supabase.from('employees').insert(payload); if (result.error) throw result.error; Alert.alert('Saved', editingId ? 'Employee updated.' : 'Employee added.'); navigation.goBack(); } catch (error: any) { Alert.alert('Unable to save employee', error.message); } setLoading(false); }
  const input = (label: string, value: string, setValue: (value: string) => void, placeholder: string, keyboardType: any = 'default') => <View style={styles.inputGroup}><Text style={[styles.label, { color: colors.muted }]}>{label}</Text><TextInput value={value} onChangeText={setValue} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType} style={[styles.input, { color: colors.text, backgroundColor: colors.card, borderColor: colors.border }]} /></View>;
  return <View style={[styles.container, { backgroundColor: colors.bg }]}><LoadingOverlay visible={loading} /><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}><ChevronLeft color={colors.text} size={22} /></TouchableOpacity><Text style={[styles.title, { color: colors.text }]}>{editingId ? 'Edit employee' : 'Add employee'}</Text><View style={{ width: 30 }} /></View><ScrollView contentContainerStyle={styles.content}><Card style={[styles.card, { backgroundColor: colors.card }]}>{input('First name', firstName, setFirstName, 'Jane')}{input('Last name', lastName, setLastName, 'Doe')}{input('Work email', email, setEmail, 'jane@company.com', 'email-address')}{input('Phone', phone, setPhone, '+383', 'phone-pad')}{input('Job title', jobTitle, setJobTitle, 'e.g. Sales manager')}{input('Department', department, setDepartment, 'e.g. Sales')}{input('Employee ID', employeeNumber, setEmployeeNumber, 'EMP-001')}{input('Start date', hireDate, setHireDate, 'YYYY-MM-DD') }<Text style={[styles.label, { color: colors.muted }]}>Status</Text><View style={styles.chips}>{(['active', 'onboarding', 'on_leave', 'terminated'] as const).map((item) => <TouchableOpacity key={item} onPress={() => setStatus(item)} style={[styles.chip, { backgroundColor: status === item ? '#004FFE' : isDark ? '#334155' : '#eef1f5' }]}><Text style={{ color: status === item ? '#fff' : colors.muted, fontSize: 11, fontWeight: '700' }}>{item.replace('_', ' ')}</Text></TouchableOpacity>)}</View></Card><Button title="Save employee" onPress={() => void save()} loading={loading} style={{ marginTop: 16 }} />{editingId ? <Button title="View private documents" variant="outline" onPress={() => navigation.navigate('EmployeeVault', { id: editingId })} icon={FileLock} style={{ marginTop: 10 }} /> : null}</ScrollView></View>;
}

const styles = StyleSheet.create({ container: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 56, paddingBottom: 13 }, back: { width: 30 }, title: { fontSize: 19, fontWeight: '800' }, content: { padding: 15, paddingBottom: 36 }, card: { padding: 16, borderRadius: 14, gap: 13 }, inputGroup: { gap: 5 }, label: { fontSize: 11, fontWeight: '700' }, input: { minHeight: 43, paddingHorizontal: 11, borderWidth: 1, borderRadius: 9, fontSize: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8 } });
