import React, { useCallback, useMemo, useState } from 'react';
import { Image, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Check, Mail, Phone, Plus, Search, UserRound, UserX } from 'lucide-react-native';
import { useTheme } from '@invoice-monorepo/hooks';
import { resolveWorkspace, supabase } from '@invoice-monorepo/api';
import { listEmployees, subscribeToHrChanges, type HrEmployee } from '@invoice-monorepo/hr';

const BLUE = '#004FFE';
export function EmployeeDirectoryScreen({ navigation }: any) {
  const { isDark } = useTheme();
  const [employees, setEmployees] = useState<HrEmployee[]>([]);
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState<'active' | 'requests'>('active');
  const [canManage, setCanManage] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const colors = { bg: isDark ? '#0f172a' : '#f7f9fc', card: isDark ? '#1e293b' : '#fff', text: isDark ? '#fff' : '#12213f', muted: isDark ? '#94a3b8' : '#6f7d96', border: isDark ? '#334155' : '#e4e9f0' };
  const load = useCallback(async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setRefreshing(true); try { const workspace = await resolveWorkspace(supabase, user.id); const own = await supabase.from('employees').select('role').eq('user_id', user.id).eq('company_id', workspace.companyId).maybeSingle(); setCanManage(['admin', 'manager'].includes(own.data?.role || '') || ['owner', 'admin'].includes(workspace.profile.role || '')); setEmployees(await listEmployees(supabase, workspace.companyIds)); } catch (error) { console.warn('Unable to load employee directory', error); } setRefreshing(false); }, []);
  useFocusEffect(useCallback(() => { void load(); const sub = supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) return undefined; try { const workspace = await resolveWorkspace(supabase, user.id); return subscribeToHrChanges(supabase, workspace.companyId, () => { void load(); }); } catch { return undefined; } }); return () => { void sub.then((remove) => remove?.()); }; }, [load]));
  const shown = useMemo(() => employees.filter((employee) => (tab === 'requests' ? employee.status === 'pending' : employee.status !== 'pending')).filter((employee) => `${employee.first_name} ${employee.last_name} ${employee.email || ''} ${employee.job_title || ''} ${employee.department || ''}`.toLowerCase().includes(query.trim().toLowerCase())), [employees, query, tab]);
  async function updateStatus(employee: HrEmployee, status: 'active' | 'terminated') { const result = await supabase.from('employees').update({ status }).eq('id', employee.id).eq('company_id', employee.company_id); if (!result.error) await load(); }
  return <View style={[styles.container, { backgroundColor: colors.bg }]}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}><UserRound color={colors.muted} size={19} /></TouchableOpacity><View><Text style={[styles.kicker, { color: BLUE }]}>PEOPLE</Text><Text style={[styles.title, { color: colors.text }]}>Employees</Text></View>{canManage ? <TouchableOpacity onPress={() => navigation.navigate('EmployeeForm')} style={styles.add}><Plus color="#fff" size={20} /></TouchableOpacity> : <View style={{ width: 38 }} />}</View>{canManage ? <View style={[styles.tabs, { backgroundColor: colors.card }]}><TouchableOpacity onPress={() => setTab('active')} style={[styles.tab, tab === 'active' && { backgroundColor: BLUE }]}><Text style={{ color: tab === 'active' ? '#fff' : colors.muted, fontSize: 11, fontWeight: '800' }}>Directory</Text></TouchableOpacity><TouchableOpacity onPress={() => setTab('requests')} style={[styles.tab, tab === 'requests' && { backgroundColor: BLUE }]}><Text style={{ color: tab === 'requests' ? '#fff' : colors.muted, fontSize: 11, fontWeight: '800' }}>Requests</Text></TouchableOpacity></View> : null}<View style={[styles.search, { backgroundColor: colors.card, borderColor: colors.border }]}><Search color={colors.muted} size={17} /><TextInput value={query} onChangeText={setQuery} placeholder="Search employees" placeholderTextColor={colors.muted} style={{ flex: 1, color: colors.text, fontSize: 12 }} /></View><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load()} tintColor={BLUE} />}>{shown.length ? shown.map((employee) => <EmployeeCard key={employee.id} employee={employee} colors={colors} canManage={canManage} onPress={() => navigation.navigate('EmployeeForm', { id: employee.id })} onApprove={() => void updateStatus(employee, 'active')} onReject={() => void updateStatus(employee, 'terminated')} />) : <View style={styles.empty}><UserRound color={BLUE} size={22} /><Text style={[styles.emptyTitle, { color: colors.text }]}>No employees found</Text><Text style={[styles.emptyText, { color: colors.muted }]}>{tab === 'requests' ? 'There are no pending employee requests.' : query ? 'Try a different search.' : 'Your organization directory is empty.'}</Text></View>}</ScrollView></View>;
}

function EmployeeCard({ employee, colors, canManage, onPress, onApprove, onReject }: { employee: HrEmployee; colors: { card: string; text: string; muted: string; border: string }; canManage: boolean; onPress: () => void; onApprove: () => void; onReject: () => void }) { return <TouchableOpacity onPress={onPress} activeOpacity={.8} style={[styles.card, { backgroundColor: colors.card }]}><View style={styles.cardTop}>{employee.avatar_url ? <Image source={{ uri: employee.avatar_url }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={{ color: BLUE, fontWeight: '800', fontSize: 12 }}>{employee.first_name[0]}{employee.last_name[0]}</Text></View>}<View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.text }]}>{employee.first_name} {employee.last_name}</Text><Text style={[styles.role, { color: colors.muted }]}>{employee.job_title || employee.department || 'Employee'}</Text></View>{employee.status === 'pending' && canManage ? <View style={styles.requestActions}><TouchableOpacity onPress={onReject} style={[styles.action, { backgroundColor: '#fff0f2' }]}><UserX size={15} color="#c43d53" /></TouchableOpacity><TouchableOpacity onPress={onApprove} style={[styles.action, { backgroundColor: '#eaf8f2' }]}><Check size={15} color="#138a62" /></TouchableOpacity></View> : <View style={[styles.statusDot, { backgroundColor: employee.status === 'active' ? '#138a62' : employee.status === 'terminated' ? '#c43d53' : '#b97709' }]} />}</View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.contactRow}><View style={styles.contact}><Mail size={13} color={colors.muted} /><Text style={[styles.contactText, { color: colors.muted }]} numberOfLines={1}>{employee.email || 'No email'}</Text></View><View style={styles.contact}><Phone size={13} color={colors.muted} /><Text style={[styles.contactText, { color: colors.muted }]}>{employee.phone || 'No phone'}</Text></View></View></TouchableOpacity>; }
const styles = StyleSheet.create({ container: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 56, paddingBottom: 12 }, back: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, kicker: { fontSize: 9, fontWeight: '800', letterSpacing: 1.4, textAlign: 'center' }, title: { marginTop: 3, fontSize: 19, fontWeight: '800' }, add: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: BLUE }, tabs: { flexDirection: 'row', gap: 5, marginHorizontal: 18, padding: 4, borderRadius: 11 }, tab: { flex: 1, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 8 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, height: 42, marginHorizontal: 18, marginTop: 13, paddingHorizontal: 12, borderWidth: 1, borderRadius: 10 }, content: { padding: 15, paddingBottom: 35 }, card: { marginBottom: 10, padding: 14, borderRadius: 14 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 43, height: 43, borderRadius: 12 }, avatarFallback: { width: 43, height: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: '#eaf0ff' }, name: { fontSize: 13, fontWeight: '800' }, role: { marginTop: 3, fontSize: 10 }, statusDot: { width: 9, height: 9, borderRadius: 5 }, requestActions: { flexDirection: 'row', gap: 6 }, action: { width: 29, height: 29, alignItems: 'center', justifyContent: 'center', borderRadius: 8 }, divider: { height: StyleSheet.hairlineWidth, marginVertical: 12 }, contactRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, contact: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 }, contactText: { flex: 1, fontSize: 9 }, empty: { alignItems: 'center', paddingTop: 60 }, emptyTitle: { marginTop: 12, fontSize: 14, fontWeight: '800' }, emptyText: { maxWidth: 260, marginTop: 5, textAlign: 'center', fontSize: 11 } });
