"use client";

import { useEffect, useState } from "react";
import { Activity, Clock3, Inbox, Timer } from "lucide-react";
import { PageHeader } from "./page-header";
import { describeEvent } from "@/lib/events";
import { formatDate, labelFor, PRIORITY_LABELS } from "@/lib/format";

type DashboardData = { open: number; resolvedToday: number; averageResponseMinutes: number; averageResolutionMinutes: number; byDepartment: Array<{ label: string; value: number }>; byPriority: Array<{ label: string; value: number }>; recentActivity: Array<{ id: string; ticket_id: string; event_name: string; payload: Record<string, unknown>; created_at: string; ticket?: { ticket_number: string; subject: string } }> };

function Metric({ label, value, hint, icon: Icon }: { label: string; value: string | number; hint: string; icon: typeof Inbox }) { return <article className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="muted text-xs">{label}</p><strong className="mt-2 block text-3xl font-semibold tracking-tight">{value}</strong><p className="muted mt-1 text-[11px]">{hint}</p></div><span className="grid size-10 place-items-center rounded-xl bg-[#edf4ff] text-[var(--blue)]"><Icon size={19} /></span></div></article>; }

function Distribution({ title, rows, labels }: { title: string; rows: Array<{ label: string; value: number }>; labels?: Record<string, string> }) { const total = rows.reduce((sum, row) => sum + row.value, 0); return <section className="card p-5"><h2 className="text-sm font-semibold">{title}</h2><div className="mt-4 grid gap-3">{rows.length ? rows.map((row) => <div key={row.label}><div className="mb-1 flex justify-between gap-3 text-xs"><span>{labels ? labelFor(row.label, labels) : labelFor(row.label, {})}</span><strong>{row.value}</strong></div><div className="h-2 overflow-hidden rounded-full bg-[#edf0f4]"><div className="h-full rounded-full bg-[var(--blue)]" style={{ width: `${total ? Math.max(5, Math.round((row.value / total) * 100)) : 0}%` }} /></div></div>) : <p className="muted text-xs">No ticket activity yet.</p>}</div></section>; }

export function DashboardView() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch("/api/dashboard", { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("Unable to load dashboard"); return response.json() as Promise<DashboardData>; }).then(setData).catch((reason: unknown) => { if ((reason as Error).name !== "AbortError") setError("Unable to load dashboard data."); }); return () => controller.abort(); }, []);
  if (error) return <div className="workspace"><PageHeader title="Dashboard" /><div className="card border-[#fecdca] bg-[#fff8f8] p-5 text-sm text-[#b42318]">{error}</div></div>;
  if (!data) return <div className="workspace"><PageHeader title="Dashboard" description="A live view of your Support workspace." /><div className="grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="skeleton h-32 rounded-xl" />)}</div></div>;
  return <div className="workspace"><PageHeader title="Dashboard" description="A live view of your Support workspace." action={{ href: "/tickets/new", label: "New ticket" }} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Open tickets" value={data.open} hint="Open, waiting, and in progress" icon={Inbox} /><Metric label="Resolved today" value={data.resolvedToday} hint="Resolved or closed since midnight" icon={Activity} /><Metric label="Average response" value={data.averageResponseMinutes ? `${data.averageResponseMinutes}m` : "—"} hint="From creation to first reply" icon={Clock3} /><Metric label="Average resolution" value={data.averageResolutionMinutes ? `${Math.round(data.averageResolutionMinutes / 60)}h` : "—"} hint="From creation to resolution" icon={Timer} /></section><section className="mt-5 grid gap-5 lg:grid-cols-2"><Distribution title="Tickets by department" rows={data.byDepartment} /><Distribution title="Tickets by priority" rows={data.byPriority} labels={PRIORITY_LABELS} /></section><section className="card mt-5 p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Recent activity</h2><span className="muted text-xs">Structured event timeline</span></div><div className="mt-4 divide-y divide-[var(--border)]">{data.recentActivity.length ? data.recentActivity.map((event) => <div key={event.id} className="flex items-start gap-3 py-3 first:pt-0 last:pb-0"><span className="mt-1 grid size-7 shrink-0 place-items-center rounded-full bg-[#edf4ff] text-[var(--blue)]"><Activity size={14} /></span><div className="min-w-0"><p className="text-xs font-medium">{describeEvent(event)}</p><p className="muted mt-1 truncate text-[11px]">{event.ticket?.ticket_number ?? event.ticket_id} · {event.ticket?.subject ?? "Ticket activity"}</p></div><time className="muted ml-auto shrink-0 text-[10px]">{formatDate(event.created_at)}</time></div>) : <p className="muted py-5 text-center text-xs">No recent activity.</p>}</div></section></div>;
}
