"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "./page-header";
import { PRIORITY_LABELS } from "@/lib/format";

type Lookup = { id: string; name: string; parent_id?: string | null; color?: string; body_text?: string };

export function TicketCreateView() {
  const router = useRouter();
  const [lookups, setLookups] = useState<{ departments: Lookup[]; categories: Lookup[]; tags: Lookup[] }>({ departments: [], categories: [], tags: [] });
  const [form, setForm] = useState({ subject: "", description: "", priority: "normal", departmentId: "", categoryId: "", sourceApplication: "operix" });
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/departments").then((response) => response.json()).then((departments: { data: Lookup[] }) => setLookups((current) => ({ ...current, departments: departments.data ?? [] }))).catch(() => undefined); fetch("/api/categories").then((response) => response.json()).then((categories: { data: Lookup[] }) => setLookups((current) => ({ ...current, categories: categories.data ?? [] }))).catch(() => undefined); fetch("/api/lookups").then((response) => response.ok ? response.json() : { data: { tags: [] } }).then((result: { data?: { tags?: Lookup[] } }) => setLookups((current) => ({ ...current, tags: result.data?.tags ?? [] }))).catch(() => undefined); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(null); const response = await fetch("/api/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ subject: form.subject, description: form.description, priority: form.priority, departmentId: form.departmentId || null, categoryId: form.categoryId || null, sourceApplication: form.sourceApplication }) }); if (!response.ok) { const result = await response.json().catch(() => null) as { error?: { message?: string } } | null; setError(result?.error?.message ?? "Unable to create ticket."); setPending(false); return; } const ticket = await response.json() as { id: string }; router.push(`/tickets/${ticket.id}`); }
  return <div className="workspace"><PageHeader title="New ticket" description="Create a ticket in the current company workspace." /><form className="grid max-w-4xl gap-5" onSubmit={submit}><section className="card grid gap-5 p-5 sm:p-6"><div className="grid gap-5 md:grid-cols-2"><label className="field md:col-span-2"><span>Subject</span><input className="input" required maxLength={240} value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} placeholder="Briefly describe the request" /></label><label className="field"><span>Priority</span><select className="select" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{Object.entries(PRIORITY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>Source application</span><select className="select" value={form.sourceApplication} onChange={(event) => setForm({ ...form, sourceApplication: event.target.value })}><option value="operix">OperiX</option><option value="internetkudo">InternetKudo</option><option value="invoice">OperiX Invoice</option><option value="hr">OperiX HR</option></select></label><label className="field"><span>Department</span><select className="select" value={form.departmentId} onChange={(event) => setForm({ ...form, departmentId: event.target.value })}><option value="">Unassigned</option>{lookups.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Category</span><select className="select" value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}><option value="">Uncategorized</option>{lookups.categories.map((item) => <option key={item.id} value={item.id}>{item.parent_id ? "↳ " : ""}{item.name}</option>)}</select></label><label className="field md:col-span-2"><span>Description</span><textarea className="textarea min-h-48" required maxLength={100000} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Add the request details…" /></label></div>{error ? <p className="rounded-md border border-[#fecdca] bg-[#fff3f2] p-3 text-xs text-[#b42318]" role="alert">{error}</p> : null}<div className="flex flex-wrap justify-end gap-3"><button type="button" className="btn" onClick={() => router.back()}>Cancel</button><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? "Creating…" : "Create ticket"}</button></div></section></form></div>;
}
