import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export type TransactionPdfInput = {
    title: string;
    number?: string;
    amount: number;
    date: string;
    description?: string;
    category?: string;
    method?: string;
    counterparty?: string;
    reference?: string;
};

const escapeHtml = (value: unknown) => String(value ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export async function generateTransactionPdf(data: TransactionPdfInput): Promise<string> {
    const html = `<!doctype html><html><head><meta charset="utf-8"><style>
      @page { size: A4; margin: 0; } body { font-family: Arial; padding: 42px; color: #172033; }
      h1 { margin: 0 0 8px; font-size: 26px; } .sub { color:#64748b; margin-bottom:32px; }
      table { width:100%; border-collapse:collapse; margin-top:24px; } td { padding:12px 0; border-bottom:1px solid #E6EBF1; }
      td:first-child { color:#64748b; width:42%; } .amount { font-size:24px; font-weight:bold; color:#004FFE; }
      .footer { margin-top:55px; color:#64748b; font-size:12px; }
    </style></head><body>
      <h1>${escapeHtml(data.title)}</h1><div class="sub">${escapeHtml(data.number || '')}</div>
      <table>
        <tr><td>Date</td><td>${escapeHtml(data.date)}</td></tr>
        ${data.counterparty ? `<tr><td>Customer / Vendor</td><td>${escapeHtml(data.counterparty)}</td></tr>` : ''}
        ${data.category ? `<tr><td>Category</td><td>${escapeHtml(data.category)}</td></tr>` : ''}
        ${data.description ? `<tr><td>Description</td><td>${escapeHtml(data.description)}</td></tr>` : ''}
        ${data.method ? `<tr><td>Payment method</td><td>${escapeHtml(data.method)}</td></tr>` : ''}
        ${data.reference ? `<tr><td>Reference</td><td>${escapeHtml(data.reference)}</td></tr>` : ''}
        <tr><td>Amount</td><td class="amount">€${data.amount.toFixed(2)}</td></tr>
      </table><div class="footer">Generated by OperiX Invoice</div>
    </body></html>`;
    const { uri } = await Print.printToFileAsync({ html, base64: false, width: 595, height: 842, margins: { top: 0, right: 0, bottom: 0, left: 0 } });
    return uri;
}

export async function shareTransactionPdf(data: TransactionPdfInput): Promise<void> {
    const uri = await generateTransactionPdf(data);
    if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: data.title, UTI: 'com.adobe.pdf' });
    }
}
