"use client";

import { useState } from "react";
import { Download, FileBarChart, Users } from "lucide-react";
import { calculateAttendanceHours } from "@invoice-monorepo/hr";
import { useHrSnapshot } from "@/lib/hr-hooks";
import { Button, Card, EmptyState, ErrorState, LoadingBlock, PageHeader, StatCard } from "./ui";

function csv(value: unknown) { return `"${String(value ?? "").replace(/"/g, '""')}"`; }

export function ReportsView() {
  const query = useHrSnapshot();
  const [department, setDepartment] = useState("all");
  const data = query.data;
  const departments = [...new Set((data?.employees || []).map((employee) => employee.department).filter(Boolean) as string[])].sort();
  const employees = (data?.employees || []).filter((employee) => department === "all" || employee.department === department);
  const attendance = (data?.attendance || []).filter((record) => employees.some((employee) => employee.id === record.employee_id));
  const leave = (data?.leaveRequests || []).filter((request) => employees.some((employee) => employee.id === request.employee_id));
  const absenceRate = attendance.length ? Math.round((attendance.filter((record) => record.status === "absent").length / attendance.length) * 100) : 0;
  function exportCsv() { const rows = [["Employee", "Department", "Status", "Hours (7 days)"], ...employees.map((employee) => [employee.first_name + " " + employee.last_name, employee.department || "", employee.status, attendance.filter((record) => record.employee_id === employee.id).reduce((sum, record) => sum + calculateAttendanceHours(record), 0).toFixed(2)])]; const blob = new Blob([rows.map((row) => row.map(csv).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `operix-hr-report-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  if (query.loading && !data) return <><PageHeader title="Reports" description="Loading HR reporting data…" /><Card><LoadingBlock lines={12} /></Card></>;
  if (query.error && !data) return <><PageHeader title="Reports" description="Operational HR reporting with permission-aware data." /><ErrorState message={query.error} onRetry={() => void query.refresh()} /></>;
  if (!data) return null;
  return <><PageHeader title="Reports" description="Headcount, attendance, absence, leave, and department reporting." action={<Button variant="secondary" onClick={exportCsv}><Download size={15} />Export CSV</Button>} /><div className="toolbar"><div className="toolbar-left"><select className="select-control" value={department} onChange={(event) => setDepartment(event.target.value)} aria-label="Department filter"><option value="all">All departments</option>{departments.map((item) => <option value={item} key={item}>{item}</option>)}</select></div><span className="muted-inline">Last 7 days · sensitive payroll data excluded</span></div><div className="stat-grid"><StatCard label="Headcount" value={employees.length} icon={<Users size={16} />} /><StatCard label="Attendance records" value={attendance.length} tone="green" icon={<FileBarChart size={16} />} /><StatCard label="Absence rate" value={`${absenceRate}%`} tone="amber" icon={<FileBarChart size={16} />} /><StatCard label="Leave requests" value={leave.length} tone="purple" icon={<FileBarChart size={16} />} /></div><Card title="Department distribution">{employees.length ? <div className="department-report">{departments.map((item) => { const count = employees.filter((employee) => employee.department === item).length; return <div className="department-row" key={item}><span>{item}</span><div className="department-track"><i style={{ width: `${employees.length ? Math.max(3, (count / employees.length) * 100) : 0}%` }} /></div><strong>{count}</strong></div>; })}{employees.some((employee) => !employee.department) ? <div className="department-row"><span>Unassigned</span><div className="department-track"><i style={{ width: `${Math.max(3, (employees.filter((employee) => !employee.department).length / employees.length) * 100)}%` }} /></div><strong>{employees.filter((employee) => !employee.department).length}</strong></div> : null}</div> : <EmptyState icon={<FileBarChart size={19} />} title="No report data" description="Reports become available when your role can access organization HR records." />}</Card><Card title="Employee attendance summary"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Employee</th><th>Department</th><th>Present days</th><th>Absent days</th><th>Hours</th></tr></thead><tbody>{employees.map((employee) => { const records = attendance.filter((record) => record.employee_id === employee.id); return <tr key={employee.id}><td>{employee.first_name} {employee.last_name}</td><td>{employee.department || "—"}</td><td>{records.filter((record) => ["present", "remote", "late"].includes(record.status)).length}</td><td>{records.filter((record) => record.status === "absent").length}</td><td>{records.reduce((sum, record) => sum + calculateAttendanceHours(record), 0).toFixed(2)}h</td></tr>; })}</tbody></table></div>{!employees.length ? <EmptyState title="No employees in this filter" /> : null}</Card></>;
}
