"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, ClipboardCheck, LogOut, Plus, UserCheck, Users } from "lucide-react";
import { createOnboardingTask, createOffboardingCase, listEmployees, listHrApprovals, listOffboardingCases, listOffboardingTasks, listOnboardingTasks, resolveHrApproval, subscribeToHrChanges, updateOffboardingCase, updateOffboardingTask, updateOnboardingTask, type HrApproval, type HrEmployee, type HrOffboardingCase, type HrOffboardingTask, type HrOnboardingTask } from "@invoice-monorepo/hr";
import { createClient } from "@/lib/supabase/client";
import { useHrWorkspace } from "@/lib/workspace";
import { Button, Card, EmptyState, ErrorState, FormMessage, LoadingBlock, Modal, PageHeader, Spinner, StatCard, StatusBadge } from "./ui";

type Tab = "onboarding" | "offboarding" | "approvals";

export function WorkflowsView() {
  const { workspace } = useHrWorkspace();
  const [tab, setTab] = useState<Tab>("onboarding");
  const [onboarding, setOnboarding] = useState<HrOnboardingTask[]>([]);
  const [offboarding, setOffboarding] = useState<HrOffboardingCase[]>([]);
  const [offboardingTasks, setOffboardingTasks] = useState<HrOffboardingTask[]>([]);
  const [approvals, setApprovals] = useState<HrApproval[]>([]);
  const [employees, setEmployees] = useState<HrEmployee[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [modal, setModal] = useState<"onboarding" | "offboarding" | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [formError, setFormError] = useState("");
  const [onboardingForm, setOnboardingForm] = useState({ employeeId: "", title: "", dueOn: "", description: "" });
  const [offboardingForm, setOffboardingForm] = useState({ employeeId: "", reason: "resignation" as HrOffboardingCase["reason"], lastWorkingDay: new Date().toISOString().slice(0, 10), notes: "" });

  const refresh = useCallback(async () => {
    const client = createClient(); if (!client || !workspace?.companyId) return;
    setLoading(true);
    try { const [onboardingRows, offboardingRows, taskRows, approvalRows, employeeRows] = await Promise.all([listOnboardingTasks(client, workspace.companyId), listOffboardingCases(client, workspace.companyId), listOffboardingTasks(client, workspace.companyId), listHrApprovals(client, workspace.companyId), listEmployees(client, [workspace.companyId])]); setOnboarding(onboardingRows); setOffboarding(offboardingRows); setOffboardingTasks(taskRows); setApprovals(approvalRows); setEmployees(employeeRows); setError(null); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load HR workflows."); }
    finally { setLoading(false); }
  }, [workspace?.companyId]);

  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { const client = createClient(); if (!client || !workspace?.companyId) return; return subscribeToHrChanges(client, workspace.companyId, () => { void refresh(); }); }, [refresh, workspace?.companyId]);

  const openApprovals = approvals.filter((approval) => approval.status === "pending");
  const onboardingDone = onboarding.filter((task) => task.status === "done").length;
  const activeOffboarding = offboarding.filter((item) => item.status === "open").length;
  const employeeName = (id: string) => { const employee = employees.find((candidate) => candidate.id === id); return employee ? `${employee.first_name} ${employee.last_name}` : "Employee"; };
  const taskProgress = useMemo(() => onboarding.length ? Math.round((onboardingDone / onboarding.length) * 100) : 0, [onboarding.length, onboardingDone]);

  function open(kind: "onboarding" | "offboarding") { setFormError(""); setMessage(""); setModal(kind); }
  function close() { if (!busy) setModal(null); }

  async function saveOnboarding(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setFormError(""); const client = createClient();
    if (!client || !workspace?.companyId || !onboardingForm.employeeId || !onboardingForm.title.trim()) { setFormError("Employee and task title are required."); return; }
    setBusy(true); try { await createOnboardingTask(client, { companyId: workspace.companyId, employeeId: onboardingForm.employeeId, title: onboardingForm.title, dueOn: onboardingForm.dueOn || undefined, description: onboardingForm.description }); setModal(null); setMessage("Onboarding task created."); setOnboardingForm({ employeeId: "", title: "", dueOn: "", description: "" }); await refresh(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : "Unable to create the onboarding task."); } finally { setBusy(false); }
  }

  async function saveOffboarding(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setFormError(""); const client = createClient();
    if (!client || !workspace?.companyId || !offboardingForm.employeeId || !offboardingForm.lastWorkingDay) { setFormError("Employee and last working day are required."); return; }
    if (!window.confirm("Start offboarding? The employee will be marked terminated and the standard checklist will be created.")) return;
    setBusy(true); try { await createOffboardingCase(client, { companyId: workspace.companyId, employeeId: offboardingForm.employeeId, reason: offboardingForm.reason, lastWorkingDay: offboardingForm.lastWorkingDay, notes: offboardingForm.notes }); setModal(null); setMessage("Offboarding started with the shared checklist."); setOffboardingForm({ employeeId: "", reason: "resignation", lastWorkingDay: new Date().toISOString().slice(0, 10), notes: "" }); await refresh(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : "Unable to start offboarding."); } finally { setBusy(false); }
  }

  async function setOnboardingStatus(task: HrOnboardingTask, status: HrOnboardingTask["status"]) { const client = createClient(); if (!client) return; try { await updateOnboardingTask(client, task.id, status); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update the task."); } }
  async function setOffboardingStatus(task: HrOffboardingTask, status: HrOffboardingTask["status"]) { const client = createClient(); if (!client) return; try { await updateOffboardingTask(client, task.id, status); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update the task."); } }
  async function resolve(approval: HrApproval, status: "approved" | "rejected" | "more_info") { const client = createClient(); if (!client) return; try { await resolveHrApproval(client, approval.id, status); setMessage("Approval updated."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to resolve the approval."); } }
  async function completeCase(caseRow: HrOffboardingCase) { const client = createClient(); if (!client) return; try { await updateOffboardingCase(client, caseRow.id, "completed"); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to complete the case."); } }

  if (loading && !onboarding.length && !offboarding.length && !approvals.length) return <><PageHeader title="Workflows" description="Loading onboarding, offboarding, and approvals…" /><Card><LoadingBlock lines={8} /></Card></>;
  if (error && !onboarding.length && !offboarding.length && !approvals.length) return <><PageHeader title="Workflows" description="Manage employee lifecycle work." /><ErrorState message={error} onRetry={() => void refresh()} /></>;

  return <>
    <PageHeader title="Workflows" description="Keep employee lifecycle work and approvals visible, accountable, and auditable." action={<><Button variant="secondary" onClick={() => open("onboarding")}><Plus size={15} />Onboarding task</Button><Button onClick={() => open("offboarding")}><LogOut size={15} />Start offboarding</Button></>} />
    {message ? <FormMessage message={message} tone="success" /> : null}{error ? <FormMessage message={error} /> : null}
    <div className="stat-grid"><StatCard label="Onboarding progress" value={`${taskProgress}%`} detail={`${onboardingDone} of ${onboarding.length} tasks done`} icon={<UserCheck size={16} />} tone="blue" /><StatCard label="Open offboarding" value={activeOffboarding} detail="Historical records retained" icon={<Archive size={16} />} tone="amber" /><StatCard label="Pending approvals" value={openApprovals.length} detail="Shared approvals inbox" icon={<ClipboardCheck size={16} />} tone="purple" /><StatCard label="Employees" value={employees.length} detail="Current directory" icon={<Users size={16} />} tone="green" /><StatCard label="Checklist items" value={onboarding.length + offboardingTasks.length} detail="Across lifecycle workflows" icon={<CheckCircle2 size={16} />} tone="blue" /></div>
    <Card><div className="filter-tabs"><button type="button" className={tab === "onboarding" ? "filter-tab-active" : ""} onClick={() => setTab("onboarding")}>Onboarding</button><button type="button" className={tab === "offboarding" ? "filter-tab-active" : ""} onClick={() => setTab("offboarding")}>Offboarding</button><button type="button" className={tab === "approvals" ? "filter-tab-active" : ""} onClick={() => setTab("approvals")}>Approvals {openApprovals.length ? `(${openApprovals.length})` : ""}</button></div></Card>
    {tab === "onboarding" ? <Card title="Onboarding checklist" action={<Button variant="ghost" onClick={() => open("onboarding")}><Plus size={14} />Add task</Button>}><div className="workflow-list">{onboarding.map((task) => <article className="workflow-row" key={task.id}><div className="workflow-row-main"><strong>{task.title}</strong><span>{task.employee ? `${task.employee.first_name} ${task.employee.last_name}` : employeeName(task.employee_id)}{task.due_on ? ` · Due ${task.due_on}` : ""}</span>{task.description ? <p>{task.description}</p> : null}</div><div className="workflow-row-controls"><StatusBadge status={task.status} /><select className="select-control compact-control" value={task.status} onChange={(event) => void setOnboardingStatus(task, event.target.value as HrOnboardingTask["status"])} aria-label="Onboarding task status"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option><option value="skipped">Skipped</option></select></div></article>)}{!onboarding.length ? <EmptyState icon={<UserCheck size={18} />} title="No onboarding tasks" description="Create a checklist for a new employee and track it here." action={<Button onClick={() => open("onboarding")}><Plus size={14} />Add task</Button>} /> : null}</div></Card> : null}
    {tab === "offboarding" ? <Card title="Offboarding cases" action={<Button variant="ghost" onClick={() => open("offboarding")}><Plus size={14} />Start case</Button>}><div className="workflow-list">{offboarding.map((caseRow) => <article className="workflow-row" key={caseRow.id}><div className="workflow-row-main"><strong>{caseRow.employee ? `${caseRow.employee.first_name} ${caseRow.employee.last_name}` : employeeName(caseRow.employee_id)}</strong><span>{caseRow.reason.replace(/_/g, " ")} · Last day {caseRow.last_working_day}</span>{caseRow.notes ? <p>{caseRow.notes}</p> : null}</div><div className="workflow-row-controls"><StatusBadge status={caseRow.status} />{caseRow.status === "open" ? <Button variant="secondary" onClick={() => void completeCase(caseRow)}>Complete</Button> : null}</div><div className="workflow-sublist">{offboardingTasks.filter((task) => task.case_id === caseRow.id).map((task) => <div className="workflow-subrow" key={task.id}><span>{task.title}</span><select className="select-control compact-control" value={task.status} onChange={(event) => void setOffboardingStatus(task, event.target.value as HrOffboardingTask["status"])} aria-label="Offboarding task status"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option><option value="skipped">Skipped</option></select></div>)}</div></article>)}{!offboarding.length ? <EmptyState icon={<Archive size={18} />} title="No offboarding cases" description="Start a case when an employee leaves; historical records stay retained." action={<Button onClick={() => open("offboarding")}><LogOut size={14} />Start case</Button>} /> : null}</div></Card> : null}
    {tab === "approvals" ? <Card title="Approvals inbox"><div className="workflow-list">{approvals.map((approval) => <article className="workflow-row" key={approval.id}><div className="workflow-row-main"><strong>{approval.resource_type.replace(/_/g, " ")}</strong><span>{approval.created_at ? new Date(approval.created_at).toLocaleString() : "No timestamp"} · {approval.status}</span>{approval.note ? <p>{approval.note}</p> : null}</div><div className="workflow-row-controls"><StatusBadge status={approval.status} />{approval.status === "pending" && approval.resource_type !== "leave_request" ? <><button type="button" className="decision-button decision-approve" onClick={() => void resolve(approval, "approved")}>Approve</button><button type="button" className="decision-button decision-reject" onClick={() => void resolve(approval, "rejected")}>Reject</button></> : approval.status === "pending" ? <a className="table-action" href="/leave">Review leave</a> : null}</div></article>)}{!approvals.length ? <EmptyState icon={<ClipboardCheck size={18} />} title="No approvals yet" description="Leave requests and other HR approval work will appear here." /> : null}</div></Card> : null}
    <Modal open={modal === "onboarding"} title="Create onboarding task" onClose={close}><form onSubmit={saveOnboarding}><div className="form-grid"><label className="form-field full">Employee<select value={onboardingForm.employeeId} onChange={(event) => setOnboardingForm({ ...onboardingForm, employeeId: event.target.value })} required><option value="">Choose employee</option>{employees.filter((employee) => employee.status !== "terminated").map((employee) => <option key={employee.id} value={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><label className="form-field full">Task title <span className="required">*</span><input value={onboardingForm.title} onChange={(event) => setOnboardingForm({ ...onboardingForm, title: event.target.value })} required placeholder="Sign employment contract" /></label><label className="form-field">Due on<input type="date" value={onboardingForm.dueOn} onChange={(event) => setOnboardingForm({ ...onboardingForm, dueOn: event.target.value })} /></label><label className="form-field full">Description<textarea value={onboardingForm.description} onChange={(event) => setOnboardingForm({ ...onboardingForm, description: event.target.value })} /></label></div>{formError ? <FormMessage message={formError} /> : null}<div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? <Spinner /> : null}Create task</Button></div></form></Modal>
    <Modal open={modal === "offboarding"} title="Start offboarding" onClose={close}><form onSubmit={saveOffboarding}><div className="form-grid"><label className="form-field full">Employee<select value={offboardingForm.employeeId} onChange={(event) => setOffboardingForm({ ...offboardingForm, employeeId: event.target.value })} required><option value="">Choose employee</option>{employees.filter((employee) => employee.status !== "terminated").map((employee) => <option key={employee.id} value={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><label className="form-field">Reason<select value={offboardingForm.reason} onChange={(event) => setOffboardingForm({ ...offboardingForm, reason: event.target.value as HrOffboardingCase["reason"] })}><option value="resignation">Resignation</option><option value="termination">Termination</option><option value="contract_expiry">Contract expiry</option><option value="retirement">Retirement</option><option value="other">Other</option></select></label><label className="form-field">Last working day<input type="date" value={offboardingForm.lastWorkingDay} onChange={(event) => setOffboardingForm({ ...offboardingForm, lastWorkingDay: event.target.value })} required /></label><label className="form-field full">Notes<textarea value={offboardingForm.notes} onChange={(event) => setOffboardingForm({ ...offboardingForm, notes: event.target.value })} /></label></div>{formError ? <FormMessage message={formError} /> : null}<div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? <Spinner /> : null}Start offboarding</Button></div></form></Modal>
  </>;
}
