import type { ReactNode } from "react";
import { money, shortDate } from "./format";

export interface FieldConfig { key:string; label:string; type?:"text"|"email"|"number"|"date"|"select"|"textarea"; required?:boolean; options?:string[]; defaultValue?:string|number; relation?:{table:string;label:string}; }
export interface ColumnConfig { key:string; label:string; render?:(row:Record<string,unknown>)=>ReactNode; }
export type PdfTemplate = "expense-register" | "income-payment" | "sales-ledger" | "vendor-ledger";
export interface ResourceConfig { title:string; singular:string; description:string; table:string; select?:string; columns:ColumnConfig[]; fields:FieldConfig[]; fixed?:Record<string,unknown>; primary:string; pdfTemplate?:PdfTemplate; }

const name = (key:string) => (row:Record<string,unknown>) => String(key.split(".").reduce<unknown>((value,part)=>value && typeof value === "object" ? (value as Record<string,unknown>)[part] : undefined,row) || "—");
const amount = (key:string) => (row:Record<string,unknown>) => money(row[key]);
const date = (key:string) => (row:Record<string,unknown>) => shortDate(row[key]);
const status = (key:string) => (row:Record<string,unknown>) => String(row[key] || "draft");

export const resourceConfigs: Record<string,ResourceConfig> = {
  recurring:{title:"Recurring Invoices",singular:"Recurring invoice",description:"Automate invoices for customers on a repeat schedule.",table:"recurring_invoice_templates",select:"*, client:clients(name)",primary:"name",columns:[{key:"name",label:"Schedule"},{key:"client.name",label:"Customer",render:name("client.name")},{key:"frequency",label:"Frequency"},{key:"next_issue_date",label:"Next issue",render:date("next_issue_date")},{key:"amount",label:"Amount",render:amount("amount")},{key:"status",label:"Status",render:status("status")}],fields:[{key:"client_id",label:"Customer",required:true,relation:{table:"clients",label:"name"}},{key:"name",label:"Schedule name",required:true},{key:"frequency",label:"Frequency",type:"select",options:["weekly","monthly","quarterly","yearly"],required:true},{key:"next_issue_date",label:"Next issue date",type:"date",required:true},{key:"due_days",label:"Payment terms (days)",type:"number",defaultValue:30},{key:"amount",label:"Recurring amount (€)",type:"number",required:true},{key:"tax_rate",label:"VAT rate (%)",type:"number",defaultValue:20},{key:"status",label:"Status",type:"select",options:["active","paused","completed"],required:true},{key:"notes",label:"Notes",type:"textarea"}]},
  reminders:{title:"Payment Reminders",singular:"Payment reminder",description:"Schedule and track reminders for upcoming and overdue invoices.",table:"invoice_reminders",select:"*, invoice:invoices(invoice_number)",primary:"scheduled_for",columns:[{key:"invoice.invoice_number",label:"Invoice",render:name("invoice.invoice_number")},{key:"reminder_type",label:"Type"},{key:"scheduled_for",label:"Scheduled",render:date("scheduled_for")},{key:"sent_at",label:"Sent",render:date("sent_at")},{key:"status",label:"Status",render:status("status")}],fields:[{key:"invoice_id",label:"Invoice",required:true,relation:{table:"invoices",label:"invoice_number"}},{key:"reminder_type",label:"Reminder type",type:"select",options:["upcoming","due_today","overdue"],required:true},{key:"scheduled_for",label:"Scheduled date",type:"date",required:true},{key:"status",label:"Status",type:"select",options:["scheduled","sent","cancelled"],required:true}]},
  "payment-links":{title:"Online Payment Links",singular:"Payment link",description:"Track Stripe checkout links created for your invoices.",table:"payment_links",select:"*, invoice:invoices(invoice_number)",primary:"created_at",columns:[{key:"invoice.invoice_number",label:"Invoice",render:name("invoice.invoice_number")},{key:"provider",label:"Provider"},{key:"amount",label:"Amount",render:amount("amount")},{key:"status",label:"Status",render:status("status")},{key:"url",label:"Checkout URL"},{key:"created_at",label:"Created",render:date("created_at")}],fields:[{key:"invoice_id",label:"Invoice",required:true,relation:{table:"invoices",label:"invoice_number"}},{key:"provider",label:"Provider",defaultValue:"stripe"},{key:"amount",label:"Amount (€)",type:"number",required:true},{key:"currency",label:"Currency",defaultValue:"eur"},{key:"status",label:"Status",type:"select",options:["pending","paid","expired"],required:true},{key:"url",label:"Checkout URL"}]},
  "tax-reports":{title:"VAT & Tax Reports",singular:"Tax report",description:"Prepare Kosovo VAT periods and export the TAK-aligned monthly Sales Book.",table:"tax_reports",primary:"period_start",pdfTemplate:"sales-ledger",columns:[{key:"period_start",label:"From",render:date("period_start")},{key:"period_end",label:"To",render:date("period_end")},{key:"country",label:"Country"},{key:"vat_rate",label:"VAT rate"},{key:"output_vat",label:"Output VAT",render:amount("output_vat")},{key:"input_vat",label:"Input VAT",render:amount("input_vat")},{key:"status",label:"Status",render:status("status")}],fields:[{key:"period_start",label:"Period start",type:"date",required:true},{key:"period_end",label:"Period end",type:"date",required:true},{key:"country",label:"Country",defaultValue:"XK",required:true},{key:"vat_rate",label:"VAT rate (%)",type:"number",defaultValue:18},{key:"output_vat",label:"Output VAT (€)",type:"number",defaultValue:0},{key:"input_vat",label:"Input VAT (€)",type:"number",defaultValue:0},{key:"status",label:"Status",type:"select",options:["draft","review","filed"],required:true},{key:"notes",label:"Notes",type:"textarea"}]},
  customers:{title:"Customers",singular:"Customer",description:"Manage customer details, balances and invoice history. Export Kartela e Blerësit from each customer row.",table:"clients",primary:"name",columns:[{key:"name",label:"Customer"},{key:"email",label:"Email"},{key:"phone",label:"Phone"},{key:"city",label:"City"},{key:"created_at",label:"Added",render:date("created_at")}],fields:[{key:"name",label:"Company or customer name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone"},{key:"address",label:"Address"},{key:"city",label:"City"},{key:"zip_code",label:"Postal code"},{key:"country",label:"Country"},{key:"tax_id",label:"Tax ID"},{key:"nui",label:"Unique identification number (NUI)"},{key:"fiscal_number",label:"Fiscal number"},{key:"vat_number",label:"VAT number"}]},
  products:{title:"Products & Services",singular:"Product",description:"Maintain pricing, stock and the complete import-cost calculation record.",table:"products",primary:"name",columns:[{key:"name",label:"Item"},{key:"sku",label:"SKU"},{key:"category",label:"Category"},{key:"unit_price",label:"Sale price",render:amount("unit_price")},{key:"unit_cost_with_vat",label:"Landed unit cost",render:amount("unit_cost_with_vat")},{key:"tax_rate",label:"VAT %"},{key:"stock_quantity",label:"Stock"}],fields:[
    {key:"name",label:"Name",required:true},{key:"sku",label:"SKU"},{key:"description",label:"Description",type:"textarea"},{key:"category",label:"Category"},{key:"unit",label:"Unit",defaultValue:"pcs"},{key:"stock_quantity",label:"Stock quantity",type:"number",defaultValue:0},
    {key:"unit_price",label:"Sale price (EUR)",type:"number",required:true},{key:"tax_rate",label:"Output VAT rate (%)",type:"number",defaultValue:18},{key:"vat_treatment",label:"Kosovo VAT treatment",type:"select",options:["standard_18","reduced_8","exempt_no_credit","exempt_with_credit","export","reverse_charge","out_of_scope"],defaultValue:"standard_18"},
    {key:"purchase_currency",label:"Supplier currency",defaultValue:"EUR"},{key:"exchange_rate",label:"Exchange rate to EUR",type:"number",defaultValue:1},{key:"supplier_unit_price",label:"Supplier unit price",type:"number",defaultValue:0},{key:"supplier_discount_percent",label:"Supplier discount (%)",type:"number",defaultValue:0},{key:"supplier_unit_price_after_discount",label:"Supplier unit price after discount (EUR)",type:"number",defaultValue:0},
    {key:"transport_cost",label:"Transport cost (EUR)",type:"number",defaultValue:0},{key:"additional_cost",label:"Additional costs (EUR)",type:"number",defaultValue:0},{key:"customs_base",label:"Customs value / base (EUR)",type:"number",defaultValue:0},{key:"customs_duty",label:"Customs duty (EUR)",type:"number",defaultValue:0},{key:"excise",label:"Excise (EUR)",type:"number",defaultValue:0},
    {key:"import_vat_rate",label:"Import VAT rate (%)",type:"number",defaultValue:18},{key:"import_vat_amount",label:"Import VAT amount (EUR)",type:"number",defaultValue:0},{key:"unit_cost_with_vat",label:"Landed unit cost incl. VAT (EUR)",type:"number",defaultValue:0},{key:"tariff_code",label:"Tariff / HS code"},{key:"country_of_origin",label:"Country of origin"},
  ]},
  expenses:{title:"Expenses",singular:"Expense",description:"Track operating costs and keep supporting records together.",table:"expenses",primary:"description",pdfTemplate:"expense-register",fixed:{type:"expense"},columns:[{key:"date",label:"Date",render:date("date")},{key:"vendor_name",label:"Supplier"},{key:"category",label:"Category"},{key:"description",label:"Description"},{key:"amount",label:"Amount",render:amount("amount")}],fields:[{key:"date",label:"Date",type:"date",required:true},{key:"vendor_name",label:"Supplier name"},{key:"category",label:"Category",type:"select",options:["Rent","Salaries","Utilities","Marketing","Travel","Office","Other"],required:true},{key:"description",label:"Description",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true}]},
  income:{title:"Income",singular:"Income record",description:"Register non-invoice income and maintain transaction evidence.",table:"expenses",primary:"description",pdfTemplate:"income-payment",fixed:{type:"income"},columns:[{key:"date",label:"Date",render:date("date")},{key:"vendor_name",label:"Payer"},{key:"category",label:"Category"},{key:"description",label:"Description"},{key:"amount",label:"Amount",render:amount("amount")}],fields:[{key:"date",label:"Date",type:"date",required:true},{key:"vendor_name",label:"Payer / subject"},{key:"category",label:"Category",defaultValue:"Other income",required:true},{key:"description",label:"Description",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true}]},
  payments:{title:"Payments",singular:"Payment",description:"Track income received against customers and invoices.",table:"payments",select:"*, client:clients(*), invoice:invoices(invoice_number,total_amount,tax_amount,due_date)",primary:"payment_number",pdfTemplate:"income-payment",columns:[{key:"payment_number",label:"Payment #"},{key:"client.name",label:"Customer",render:name("client.name")},{key:"payment_date",label:"Date",render:date("payment_date")},{key:"amount",label:"Amount",render:amount("amount")},{key:"payment_method",label:"Method"}],fields:[{key:"client_id",label:"Customer",relation:{table:"clients",label:"name"}},{key:"invoice_id",label:"Invoice",relation:{table:"invoices",label:"invoice_number"}},{key:"payment_number",label:"Payment number",required:true},{key:"payment_date",label:"Payment date",type:"date",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true},{key:"payment_method",label:"Payment method",type:"select",options:["cash","bank","card"],required:true},{key:"bank_reference",label:"Bank reference"},{key:"notes",label:"Notes",type:"textarea"}]},
  vendors:{title:"Vendors",singular:"Vendor",description:"Manage suppliers, contacts and outgoing activity.",table:"vendors",primary:"name",pdfTemplate:"vendor-ledger",columns:[{key:"name",label:"Vendor"},{key:"email",label:"Email"},{key:"phone",label:"Phone"},{key:"city",label:"City"},{key:"country",label:"Country"}],fields:[{key:"name",label:"Vendor name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone"},{key:"address",label:"Address"},{key:"city",label:"City"},{key:"country",label:"Country"},{key:"tax_id",label:"Tax ID"},{key:"notes",label:"Notes",type:"textarea"}]},
  "supplier-bills":{title:"Supplier Bills",singular:"Supplier bill",description:"Record incoming bills and monitor what is due.",table:"supplier_bills",select:"*, vendor:vendors(name)",primary:"bill_number",columns:[{key:"bill_number",label:"Bill #"},{key:"vendor.name",label:"Vendor",render:name("vendor.name")},{key:"issue_date",label:"Issue Date",render:date("issue_date")},{key:"due_date",label:"Due Date",render:date("due_date")},{key:"total_amount",label:"Total",render:amount("total_amount")},{key:"status",label:"Status",render:status("status")}],fields:[{key:"vendor_id",label:"Vendor",required:true,relation:{table:"vendors",label:"name"}},{key:"bill_number",label:"Bill number",required:true},{key:"issue_date",label:"Issue date",type:"date",required:true},{key:"due_date",label:"Due date",type:"date"},{key:"total_amount",label:"Total (€)",type:"number",required:true},{key:"tax_amount",label:"Tax (€)",type:"number",defaultValue:0},{key:"status",label:"Status",type:"select",options:["unpaid","partial","paid"],required:true},{key:"notes",label:"Notes",type:"textarea"}]},
  contracts:{title:"Contracts",singular:"Contract",description:"Create and track agreements and signatures.",table:"contracts",select:"*, client:clients(name)",primary:"title",columns:[{key:"title",label:"Contract"},{key:"client.name",label:"Customer",render:name("client.name")},{key:"type",label:"Type"},{key:"status",label:"Status",render:status("status")},{key:"created_at",label:"Created",render:date("created_at")}],fields:[{key:"title",label:"Contract title",required:true},{key:"client_id",label:"Customer",relation:{table:"clients",label:"name"}},{key:"type",label:"Type",type:"select",options:["service_agreement","nda","employment","general"],required:true},{key:"status",label:"Status",type:"select",options:["draft","signed","active","terminated"],required:true},{key:"html_body",label:"Contract body",type:"textarea"}]},
  "vendor-payments":{title:"Vendor Payments",singular:"Vendor payment",description:"Track outgoing payments made to suppliers.",table:"vendor_payments",select:"*, vendor:vendors(name)",primary:"payment_number",columns:[{key:"payment_number",label:"Payment #"},{key:"vendor.name",label:"Vendor",render:name("vendor.name")},{key:"payment_date",label:"Date",render:date("payment_date")},{key:"amount",label:"Amount",render:amount("amount")},{key:"payment_method",label:"Method"}],fields:[{key:"vendor_id",label:"Vendor",required:true,relation:{table:"vendors",label:"name"}},{key:"payment_number",label:"Payment number",required:true},{key:"payment_date",label:"Payment date",type:"date",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true},{key:"payment_method",label:"Method",type:"select",options:["bank","cash","card"],required:true},{key:"bank_reference",label:"Bank reference"},{key:"notes",label:"Notes",type:"textarea"}]},
};
