import type { ReactNode } from "react";
import { money, shortDate } from "./format";

export interface FieldConfig { key:string; label:string; type?:"text"|"email"|"number"|"date"|"select"|"textarea"; required?:boolean; options?:string[]; defaultValue?:string|number; relation?:{table:string;label:string}; }
export interface ColumnConfig { key:string; label:string; render?:(row:Record<string,unknown>)=>ReactNode; }
export interface ResourceConfig { title:string; singular:string; description:string; table:string; select?:string; columns:ColumnConfig[]; fields:FieldConfig[]; fixed?:Record<string,unknown>; primary:string; }

const name = (key:string) => (row:Record<string,unknown>) => String(key.split(".").reduce<unknown>((value,part)=>value && typeof value === "object" ? (value as Record<string,unknown>)[part] : undefined,row) || "—");
const amount = (key:string) => (row:Record<string,unknown>) => money(row[key]);
const date = (key:string) => (row:Record<string,unknown>) => shortDate(row[key]);
const status = (key:string) => (row:Record<string,unknown>) => String(row[key] || "draft");

export const resourceConfigs: Record<string,ResourceConfig> = {
  customers:{title:"Customers",singular:"Customer",description:"Manage customer details, balances and invoice history.",table:"clients",primary:"name",columns:[{key:"name",label:"Customer"},{key:"email",label:"Email"},{key:"phone",label:"Phone"},{key:"city",label:"City"},{key:"created_at",label:"Added",render:date("created_at")}],fields:[{key:"name",label:"Company or customer name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone"},{key:"address",label:"Address"},{key:"city",label:"City"},{key:"zip_code",label:"Postal code"},{key:"country",label:"Country"},{key:"tax_id",label:"Tax ID"}]},
  products:{title:"Products & Services",singular:"Product",description:"Maintain pricing, tax rates and stock information.",table:"products",primary:"name",columns:[{key:"name",label:"Item"},{key:"sku",label:"SKU"},{key:"category",label:"Category"},{key:"unit_price",label:"Unit Price",render:amount("unit_price")},{key:"tax_rate",label:"Tax"},{key:"stock_quantity",label:"Stock"}],fields:[{key:"name",label:"Name",required:true},{key:"sku",label:"SKU"},{key:"description",label:"Description",type:"textarea"},{key:"category",label:"Category"},{key:"unit",label:"Unit",defaultValue:"pcs"},{key:"unit_price",label:"Unit price",type:"number",required:true},{key:"tax_rate",label:"Tax rate (%)",type:"number",defaultValue:18},{key:"stock_quantity",label:"Stock quantity",type:"number",defaultValue:0}]},
  expenses:{title:"Expenses",singular:"Expense",description:"Track operating costs and keep supporting records together.",table:"expenses",primary:"description",fixed:{type:"expense"},columns:[{key:"date",label:"Date",render:date("date")},{key:"category",label:"Category"},{key:"description",label:"Description"},{key:"amount",label:"Amount",render:amount("amount")}],fields:[{key:"date",label:"Date",type:"date",required:true},{key:"category",label:"Category",type:"select",options:["Rent","Salaries","Utilities","Marketing","Travel","Office","Other"],required:true},{key:"description",label:"Description",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true}]},
  income:{title:"Income",singular:"Income record",description:"Register non-invoice income and maintain transaction evidence.",table:"expenses",primary:"description",fixed:{type:"income"},columns:[{key:"date",label:"Date",render:date("date")},{key:"category",label:"Category"},{key:"description",label:"Description"},{key:"amount",label:"Amount",render:amount("amount")}],fields:[{key:"date",label:"Date",type:"date",required:true},{key:"category",label:"Category",defaultValue:"Other income",required:true},{key:"description",label:"Description",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true}]},
  payments:{title:"Payments",singular:"Payment",description:"Track income received against customers and invoices.",table:"payments",select:"*, client:clients(name)",primary:"payment_number",columns:[{key:"payment_number",label:"Payment #"},{key:"client.name",label:"Customer",render:name("client.name")},{key:"payment_date",label:"Date",render:date("payment_date")},{key:"amount",label:"Amount",render:amount("amount")},{key:"payment_method",label:"Method"}],fields:[{key:"client_id",label:"Customer",relation:{table:"clients",label:"name"}},{key:"invoice_id",label:"Invoice",relation:{table:"invoices",label:"invoice_number"}},{key:"payment_number",label:"Payment number",required:true},{key:"payment_date",label:"Payment date",type:"date",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true},{key:"payment_method",label:"Payment method",type:"select",options:["cash","bank","card"],required:true},{key:"bank_reference",label:"Bank reference"},{key:"notes",label:"Notes",type:"textarea"}]},
  vendors:{title:"Vendors",singular:"Vendor",description:"Manage suppliers, contacts and outgoing activity.",table:"vendors",primary:"name",columns:[{key:"name",label:"Vendor"},{key:"email",label:"Email"},{key:"phone",label:"Phone"},{key:"city",label:"City"},{key:"country",label:"Country"}],fields:[{key:"name",label:"Vendor name",required:true},{key:"email",label:"Email",type:"email"},{key:"phone",label:"Phone"},{key:"address",label:"Address"},{key:"city",label:"City"},{key:"country",label:"Country"},{key:"tax_id",label:"Tax ID"},{key:"notes",label:"Notes",type:"textarea"}]},
  "supplier-bills":{title:"Supplier Bills",singular:"Supplier bill",description:"Record incoming bills and monitor what is due.",table:"supplier_bills",select:"*, vendor:vendors(name)",primary:"bill_number",columns:[{key:"bill_number",label:"Bill #"},{key:"vendor.name",label:"Vendor",render:name("vendor.name")},{key:"issue_date",label:"Issue Date",render:date("issue_date")},{key:"due_date",label:"Due Date",render:date("due_date")},{key:"total_amount",label:"Total",render:amount("total_amount")},{key:"status",label:"Status",render:status("status")}],fields:[{key:"vendor_id",label:"Vendor",required:true,relation:{table:"vendors",label:"name"}},{key:"bill_number",label:"Bill number",required:true},{key:"issue_date",label:"Issue date",type:"date",required:true},{key:"due_date",label:"Due date",type:"date"},{key:"total_amount",label:"Total (€)",type:"number",required:true},{key:"tax_amount",label:"Tax (€)",type:"number",defaultValue:0},{key:"status",label:"Status",type:"select",options:["unpaid","partial","paid"],required:true},{key:"notes",label:"Notes",type:"textarea"}]},
  contracts:{title:"Contracts",singular:"Contract",description:"Create and track agreements and signatures.",table:"contracts",select:"*, client:clients(name)",primary:"title",columns:[{key:"title",label:"Contract"},{key:"client.name",label:"Customer",render:name("client.name")},{key:"type",label:"Type"},{key:"status",label:"Status",render:status("status")},{key:"created_at",label:"Created",render:date("created_at")}],fields:[{key:"title",label:"Contract title",required:true},{key:"client_id",label:"Customer",relation:{table:"clients",label:"name"}},{key:"type",label:"Type",type:"select",options:["service_agreement","nda","employment","general"],required:true},{key:"status",label:"Status",type:"select",options:["draft","signed","active","terminated"],required:true},{key:"html_body",label:"Contract body",type:"textarea"}]},
  "vendor-payments":{title:"Vendor Payments",singular:"Vendor payment",description:"Track outgoing payments made to suppliers.",table:"vendor_payments",select:"*, vendor:vendors(name)",primary:"payment_number",columns:[{key:"payment_number",label:"Payment #"},{key:"vendor.name",label:"Vendor",render:name("vendor.name")},{key:"payment_date",label:"Date",render:date("payment_date")},{key:"amount",label:"Amount",render:amount("amount")},{key:"payment_method",label:"Method"}],fields:[{key:"vendor_id",label:"Vendor",required:true,relation:{table:"vendors",label:"name"}},{key:"payment_number",label:"Payment number",required:true},{key:"payment_date",label:"Payment date",type:"date",required:true},{key:"amount",label:"Amount (€)",type:"number",required:true},{key:"payment_method",label:"Method",type:"select",options:["bank","cash","card"],required:true},{key:"bank_reference",label:"Bank reference"},{key:"notes",label:"Notes",type:"textarea"}]},
};
