-- OperiX Desk legacy tables in the shared Supabase/Postgres database.
--
-- The original Desk copy kept these migrations under its app directory, so a
-- fresh OperiX database would otherwise reach the shared-workspace migration
-- without the legacy tables it extends. This migration is idempotent for
-- installations that already applied the app-local Desk migrations.

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'userrole') then
    create type public.userrole as enum ('employee', 'team_leader', 'manager', 'admin');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'resourcetype') then
    create type public.resourcetype as enum ('desk', 'room', 'amenity');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'reservationstatus') then
    create type public.reservationstatus as enum ('active', 'cancelled', 'resource_removed');
  end if;
end
$$;

alter type public.resourcetype add value if not exists 'amenity';

create table if not exists public.users (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  hashed_password varchar(255) not null,
  role public.userrole not null default 'employee',
  full_name varchar(255) not null,
  job_title varchar(150),
  team_name varchar(150),
  department varchar(120),
  specialization varchar(50),
  experience_level varchar(20),
  skills jsonb,
  availability double precision,
  profile_image_path varchar(255),
  team_leader_id integer references public.users(id),
  supabase_user_id varchar(64),
  company_id varchar(64),
  password_reset_token_hash varchar(255),
  password_reset_expires_at timestamptz,
  must_change_password boolean not null default false
);

create table if not exists public.resources (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  type public.resourcetype not null,
  building varchar(120) not null default 'HQ - Prishtina',
  floor varchar(50) not null,
  zone varchar(100) not null,
  floor_plan_x double precision,
  floor_plan_y double precision,
  capacity integer not null default 1,
  amenities text,
  is_active boolean not null default true,
  restricted_to_team_leaders boolean not null default false,
  desk_type varchar(100),
  company_id varchar(64)
);

create table if not exists public.reservations (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id),
  resource_id integer not null references public.resources(id),
  date date not null,
  start_time time,
  end_time time,
  status public.reservationstatus not null default 'active',
  company_id varchar(64)
);

create table if not exists public.floor_plans (
  id integer generated by default as identity primary key,
  name varchar(150),
  building varchar(100) not null default 'HQ',
  floor varchar(50) not null,
  image_path varchar(500) not null,
  company_id varchar(64)
);

create table if not exists public.favorites (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  resource_id integer not null references public.resources(id) on delete cascade,
  company_id varchar(64),
  constraint uq_favorites_user_resource unique (user_id, resource_id)
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  actor_id integer not null references public.users(id),
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id integer,
  details text,
  created_at timestamptz not null default now(),
  company_id varchar(64)
);

create table if not exists public.desk_device_tokens (
  id bigint generated by default as identity primary key,
  company_id varchar(64) not null,
  user_id integer not null references public.users(id) on delete cascade,
  push_token text not null unique,
  platform varchar(20) not null,
  device_name varchar(120),
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now()
);
create index if not exists operix_desk_device_tokens_user_scope_idx
  on public.desk_device_tokens (company_id, user_id, is_active);

-- Complete partially-created app-local tables without overwriting any data.
alter table public.users add column if not exists department varchar(120);
alter table public.users add column if not exists specialization varchar(50);
alter table public.users add column if not exists experience_level varchar(20);
alter table public.users add column if not exists skills jsonb;
alter table public.users add column if not exists availability double precision;
alter table public.users add column if not exists profile_image_path varchar(255);
alter table public.users add column if not exists team_leader_id integer;
alter table public.users add column if not exists supabase_user_id varchar(64);
alter table public.users add column if not exists company_id varchar(64);
alter table public.users add column if not exists password_reset_token_hash varchar(255);
alter table public.users add column if not exists password_reset_expires_at timestamptz;
alter table public.users add column if not exists must_change_password boolean not null default false;
alter table public.resources add column if not exists restricted_to_team_leaders boolean not null default false;
alter table public.resources add column if not exists company_id varchar(64);
alter table public.reservations add column if not exists start_time time;
alter table public.reservations add column if not exists end_time time;
alter table public.reservations add column if not exists company_id varchar(64);
alter table public.floor_plans add column if not exists name varchar(150);
alter table public.floor_plans add column if not exists company_id varchar(64);
alter table public.favorites add column if not exists company_id varchar(64);
alter table public.audit_logs add column if not exists company_id varchar(64);

-- `public.users` is deny-by-default because it contains password-hash
-- compatibility fields. RLS policies on Desk child tables use this narrowly
-- scoped security-definer predicate instead of exposing that table to clients.
create or replace function private.desk_user_matches_auth(
  p_user_id integer,
  p_company_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.users desk_user
    where desk_user.id = p_user_id
      and desk_user.supabase_user_id = (select auth.uid())::text
      and desk_user.company_id = p_company_id::text
  );
$$;

revoke all on function private.desk_user_matches_auth(integer, uuid) from public;
grant execute on function private.desk_user_matches_auth(integer, uuid) to authenticated, service_role;

alter table public.desk_device_tokens enable row level security;
drop policy if exists operix_desk_device_tokens_manage on public.desk_device_tokens;
create policy operix_desk_device_tokens_manage on public.desk_device_tokens
for all to authenticated
using (
  company_id is not null
  and public.can_access_company(company_id::uuid)
  and private.desk_user_matches_auth(user_id, company_id::uuid)
)
with check (
  company_id is not null
  and public.can_access_company(company_id::uuid)
  and private.desk_user_matches_auth(user_id, company_id::uuid)
);

create index if not exists ix_users_email on public.users (email);
create index if not exists ix_users_role on public.users (role);
create index if not exists ix_users_team_name on public.users (team_name);
create index if not exists ix_users_team_leader_id on public.users (team_leader_id);
create index if not exists ix_users_password_reset_token_hash on public.users (password_reset_token_hash)
where password_reset_token_hash is not null;
create index if not exists ix_resources_active_type on public.resources (is_active, type);
create index if not exists ix_resources_floor_zone on public.resources (floor, zone);
create index if not exists ix_resources_floor_name on public.resources (floor, name);
create index if not exists ix_resources_zone on public.resources (zone);
create index if not exists ix_reservations_user_id on public.reservations (user_id);
create index if not exists ix_reservations_resource_id on public.reservations (resource_id);
create index if not exists ix_reservations_date on public.reservations (date);
create index if not exists ix_reservations_status on public.reservations (status);
create index if not exists ix_reservations_user_date on public.reservations (user_id, date);
create index if not exists ix_reservations_resource_date_status on public.reservations (resource_id, date, status);
create index if not exists ix_floor_plans_floor on public.floor_plans (floor);
create index if not exists ix_favorites_user_id on public.favorites (user_id);
create index if not exists ix_favorites_resource_id on public.favorites (resource_id);
create index if not exists ix_audit_logs_actor_id on public.audit_logs (actor_id);
create index if not exists ix_audit_logs_created_at on public.audit_logs (created_at desc);
create index if not exists ix_audit_logs_entity on public.audit_logs (entity_type, entity_id);

-- A global floor uniqueness constraint would make two companies unable to
-- both have a "Floor 1". The shared-workspace migration adds the scoped key.
alter table public.floor_plans drop constraint if exists floor_plans_floor_key;
alter table public.reservations drop constraint if exists uq_resource_date;

create unique index if not exists operix_desk_floor_plans_company_floor_unique
  on public.floor_plans (company_id, floor)
  where company_id is not null;

alter table public.users enable row level security;
alter table public.resources enable row level security;
alter table public.reservations enable row level security;
alter table public.floor_plans enable row level security;
alter table public.favorites enable row level security;
alter table public.audit_logs enable row level security;
