"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Eye, FileDown, Plus, Save, Trash2 } from "lucide-react";
import { addDays, isoToday, money } from "@/lib/format";
import { cashAllowed, invoiceTotals, paymentState } from "@/lib/invoice-calculations";
import type { ClientRow, InvoiceDraft, InvoiceEditorItem, InvoiceTemplate, InvoiceTemplateConfig, PaymentMethod, ProductRow } from "@/lib/models";
import { createClient } from "@/lib/supabase/client";
import { useBusinessData } from "@/hooks/use-business-data";
import { useWorkspace } from "@/hooks/use-workspace";
import { InvoiceDocument } from "./invoice-document";
import type { DocumentCompany } from "./invoice-document";
import { templateConfigFromRow, type InvoiceTemplateRow } from "@/lib/invoice-template-settings";
import { openInvoicePdf } from "@/lib/pdf-client";

function blankItem(id=crypto.randomUUID()):InvoiceEditorItem{return{id,description:"",quantity:1,unit_price:0,tax_rate:18,discount:0,unit:"pcs"};}

export function InvoiceEditor() {
  const router=useRouter(); const search=useSearchParams(); const today=isoToday(); const editId=search.get("edit"); const convertId=search.get("convert");
  const clientsQuery=useBusinessData<ClientRow>("clients");
  const productsQuery=useBusinessData<ProductRow>("products");
  const workspace=useWorkspace();
  const clients=clientsQuery.data; const products=productsQuery.data;
  const [template,setTemplate]=useState<InvoiceTemplate>("corporate");
  const [templateConfig,setTemplateConfig]=useState<InvoiceTemplateConfig>({style:"corporate",pageSize:"A4",showSignature:true,showStamp:true,showNotes:true,showDiscount:true,showTax:true,showBankDetails:true});
  const prefix=search.get("type")==="offer"?"QUO":"INV";
  const [draft,setDraft]=useState<InvoiceDraft>(()=>({client_id:"",invoice_number:`${prefix}-${new Date().getFullYear()}-000000`,issue_date:today,due_date:addDays(today,14),payment_method:"bank",amount_received:0,notes:"",status:"draft",items:[blankItem("new-item")] }));
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [previewMode,setPreviewMode]=useState(false);
  useEffect(()=>{const config=(workspace.company?.template_config||workspace.profile?.template_config||{}) as InvoiceTemplateConfig;const style=config.style||((config.pageSize==="Receipt")?"thermal":"corporate");queueMicrotask(()=>{setTemplate(style);setTemplateConfig(current=>({...current,...config,style}));});},[workspace.company?.template_config,workspace.profile?.template_config]);
  useEffect(()=>{if(!workspace.user)return;const supabase=createClient();if(!supabase)return;void supabase.from("invoice_templates").select("*").eq("user_id",workspace.user.id).eq("is_default",true).maybeSingle().then(({data,error})=>{if(error){setMessage(error.message);return;}if(!data)return;const shared=templateConfigFromRow(data as InvoiceTemplateRow);setTemplateConfig(current=>({...current,...shared}));if(!editId)setDraft(current=>({...current,due_date:addDays(current.issue_date,shared.defaultDueDays||30),items:current.items.map(item=>({...item,tax_rate:shared.defaultTaxRate??item.tax_rate}))}));});},[workspace.user,editId]);
  useEffect(()=>{if(!editId)return;const supabase=createClient();if(!supabase)return;void supabase.from("invoices").select("*, items:invoice_items(*)").eq("id",editId).single().then(({data,error})=>{if(error){setMessage(error.message);return;}setDraft({client_id:data.client_id||"",invoice_number:data.invoice_number,issue_date:data.issue_date,due_date:data.due_date||data.issue_date,payment_method:data.payment_method||"bank",amount_received:Number(data.amount_received||0),notes:data.notes||"",status:data.status,items:(data.items||[]).map((item:Record<string,unknown>)=>({id:String(item.id),product_id:item.product_id?String(item.product_id):undefined,description:String(item.description||""),quantity:Number(item.quantity||0),unit_price:Number(item.unit_price||0),tax_rate:Number(item.tax_rate||0),discount:Number(item.discount||0),unit:String(item.unit||"pcs"),sku:item.sku?String(item.sku):undefined}))});const style=data.template_id==="thermal"||data.paper_size==="Receipt"?"thermal":"corporate";setTemplate(style);});},[editId]);
  useEffect(()=>{if(!convertId||editId)return;const supabase=createClient();if(!supabase)return;void supabase.from("invoices").select("*, items:invoice_items(*)").eq("id",convertId).single().then(({data,error})=>{if(error){setMessage(error.message);return;}const source=String(data.invoice_number||"");setDraft({client_id:data.client_id||"",invoice_number:`INV-${new Date().getFullYear()}-${source.replace(/\\D/g,"").slice(-6).padStart(6,"0")}`,issue_date:today,due_date:data.due_date||addDays(today,14),payment_method:data.payment_method||"bank",amount_received:0,notes:data.notes||"Converted from quote",status:"draft",items:(data.items||[]).map((item:Record<string,unknown>)=>({id:crypto.randomUUID(),product_id:item.product_id?String(item.product_id):undefined,description:String(item.description||""),quantity:Number(item.quantity||0),unit_price:Number(item.unit_price||0),tax_rate:Number(item.tax_rate||0),discount:Number(item.discount||0),unit:String(item.unit||"pcs"),sku:item.sku?String(item.sku):undefined}))});});},[convertId,editId,today]);
  const totals=useMemo(()=>invoiceTotals(draft),[draft]); const payment=paymentState(totals.total,draft.amount_received); const client=clients.find((item)=>item.id===draft.client_id);
  function update<K extends keyof InvoiceDraft>(key:K,value:InvoiceDraft[K]){setDraft(current=>({...current,[key]:value}));}
  function updateItem(id:string,key:keyof InvoiceEditorItem,value:string|number){setDraft(current=>({...current,items:current.items.map(item=>item.id===id?{...item,[key]:value}:item)}));}
  function chooseProduct(id:string,productId:string){const product=products.find((row)=>row.id===productId);if(!product)return;setDraft(current=>({...current,items:current.items.map(item=>item.id===id?{...item,product_id:product.id,description:product.name,unit_price:product.unit_price,tax_rate:product.tax_rate||0,unit:product.unit||"pcs",sku:product.sku}:item)}));}
  function chooseMethod(method:PaymentMethod){if(method==="cash"&&!cashAllowed(totals.total))return;setDraft(current=>({...current,payment_method:method,amount_received:method==="cash"?current.amount_received:0}));}
  async function save(status:"draft"|"sent"){
    if(!draft.client_id||!draft.items.length||draft.items.some(item=>!item.description)){setMessage("Select a customer and complete every item.");return;} setSaving(true);setMessage("");
    const supabase=createClient(); if(!supabase){setMessage("Supabase is not configured.");setSaving(false);return;}
    const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Your session has expired.");setSaving(false);return;}
    const invoicePayload={user_id:user.id,company_id:workspace.companyId,client_id:draft.client_id,invoice_number:draft.invoice_number,issue_date:draft.issue_date,due_date:draft.due_date,status:payment.paid?"paid":status,type:search.get("type")==="offer"?"offer":"invoice",discount_amount:totals.discount,tax_amount:totals.tax,total_amount:totals.total,notes:draft.notes,template_id:template,payment_method:draft.payment_method,amount_received:draft.amount_received,change_amount:payment.change,paper_size:template==="thermal"?"Receipt":"A4"};
    let invoiceId=editId;
    if(editId){const updateResult=await supabase.from("invoices").update(invoicePayload).eq("id",editId).select("id").single();if(updateResult.error){setMessage(updateResult.error.message);setSaving(false);return;}const deleteResult=await supabase.from("invoice_items").delete().eq("invoice_id",editId);if(deleteResult.error){setMessage(deleteResult.error.message);setSaving(false);return;}}else{const insertResult=await supabase.from("invoices").insert(invoicePayload).select("id").single();if(insertResult.error){setMessage(insertResult.error.message);setSaving(false);return;}invoiceId=insertResult.data.id;}
    const items=draft.items.map(item=>({invoice_id:invoiceId,product_id:item.product_id||null,description:item.description,quantity:item.quantity,unit_price:item.unit_price,tax_rate:item.tax_rate,discount:item.discount,amount:item.quantity*item.unit_price*(1-item.discount/100)*(1+item.tax_rate/100),unit:item.unit,sku:item.sku}));const itemResult=await supabase.from("invoice_items").insert(items);if(itemResult.error){setMessage(itemResult.error.message);setSaving(false);return;}if(search.get("type")!=="offer"){await supabase.from("invoice_reminders").delete().eq("invoice_id",invoiceId);await supabase.from("invoice_reminders").insert([{user_id:user.id,company_id:workspace.companyId,invoice_id:invoiceId,reminder_type:"upcoming",scheduled_for:addDays(draft.due_date,-3),status:"scheduled"},{user_id:user.id,company_id:workspace.companyId,invoice_id:invoiceId,reminder_type:"overdue",scheduled_for:addDays(draft.due_date,1),status:"scheduled"}]);}setSaving(false);router.push(`/invoices/preview/${encodeURIComponent(draft.invoice_number)}`);router.refresh();
  }
  async function print(receipt=false){setMessage("");try{await openInvoicePdf({draft,client,company,receipt,template,config:templateConfig},`${draft.invoice_number}.pdf`);}catch(error){setMessage(error instanceof Error?error.message:"The PDF could not be generated.");}}
  async function download(){setMessage("");const response=await fetch("/api/pdf",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draft,client,company,receipt:false,template,config:templateConfig})});if(!response.ok){setMessage("The PDF could not be generated. Try printing the preview.");return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${draft.invoice_number}.pdf`;a.click();URL.revokeObjectURL(url);}
  const source=workspace.company||workspace.profile;const company:DocumentCompany={name:source?.company_name||workspace.company?.name||"",email:source?.email||"",phone:source?.phone||"",address:source?.address||"",city:[workspace.company?.city,workspace.company?.country].filter(Boolean).join(", "),taxId:source?.tax_id||"",bankName:source?.bank_name||"",iban:source?.bank_iban||"",website:source?.website||"",signatureUrl:source?.signature_url};
  const dataError=clientsQuery.error||productsQuery.error||workspace.error;
  return <div className="p-4 lg:p-6 max-w-[1700px] mx-auto"><header className="flex flex-wrap items-center gap-3 mb-5"><div><h1 className="page-title">{editId?"Edit":"Create"} {search.get("type")==="offer"?"Quote":"Invoice"}</h1><p className="text-xs mt-1.5"><span className="text-[#004ffe]">Invoices</span><span className="muted"> &nbsp;/&nbsp; {editId?"Edit":"Create"}</span></p></div><div className="ml-auto flex gap-2"><button className="btn" onClick={()=>save("draft")} disabled={saving}>Save as Draft</button><button className="btn" onClick={()=>setPreviewMode(!previewMode)}><Eye size={16}/>Preview</button><button className="btn btn-primary" onClick={()=>save("sent")} disabled={saving}><Save size={16}/>{saving?"Saving…":editId?"Update":"Save Invoice"}</button></div></header>{dataError&&<p className="mb-4 p-3 rounded bg-[#fff3f2] text-[#d92d20] text-xs">{dataError}</p>}{message&&<p className="mb-4 p-3 rounded bg-[#fff3f2] text-[#d92d20] text-xs">{message}</p>}
    <div className={`grid gap-4 ${previewMode?"grid-cols-1":"xl:grid-cols-[minmax(0,1.55fr)_minmax(430px,1fr)]"}`}><div className={`${previewMode?"hidden":"grid gap-3"} min-w-0`}>
      <FormCard title="1. Customer Information"><div className="grid sm:grid-cols-2 gap-4"><label className="field"><span>Customer *</span><select className="select" value={draft.client_id} onChange={(e)=>update("client_id",e.target.value)}><option value="">Select customer</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Email</span><input className="input" value={client?.email||""} readOnly/></label><label className="field sm:col-span-2"><span>Billing address</span><textarea className="textarea min-h-16" value={`${client?.address||""}\n${client?.city||""} ${client?.country||""}`} readOnly/></label>{!clientsQuery.loading&&!clients.length?<p className="sm:col-span-2 text-xs text-[#d92d20]">Create a customer before issuing an invoice.</p>:null}</div></FormCard>
      <FormCard title="2. Invoice Details"><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Invoice Number" value={draft.invoice_number} onChange={v=>update("invoice_number",v)}/><Field label="Issue Date" type="date" value={draft.issue_date} onChange={v=>update("issue_date",v)}/><Field label="Due Date" type="date" value={draft.due_date} onChange={v=>update("due_date",v)}/><label className="field"><span>Currency</span><select className="select"><option>EUR — Euro (€)</option></select></label><label className="field"><span>Payment method</span><select className="select" value={draft.payment_method} onChange={(e)=>chooseMethod(e.target.value as PaymentMethod)}><option value="bank">Bank transfer</option><option value="cash" disabled={!cashAllowed(totals.total)}>Cash</option><option value="card">Card</option></select></label><Field label="Reference (Optional)" value="" onChange={()=>{}}/></div></FormCard>
      <FormCard title="3. Items"><div className="table-wrap"><table className="data-table min-w-[740px]"><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Tax</th><th>Discount</th><th>Total</th><th/></tr></thead><tbody>{draft.items.map(item=><tr key={item.id}><td><select className="select min-w-40" value={item.product_id||""} onChange={(e)=>chooseProduct(item.id,e.target.value)}><option value="">Custom item</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="input mt-2 block min-w-40" value={item.description} onChange={(e)=>updateItem(item.id,"description",e.target.value)}/></td><td><input className="input w-16" type="number" min=".01" step=".01" value={item.quantity} onChange={(e)=>updateItem(item.id,"quantity",Number(e.target.value))}/></td><td><input className="input w-24" type="number" step=".01" value={item.unit_price} onChange={(e)=>updateItem(item.id,"unit_price",Number(e.target.value))}/></td><td><input className="input" style={{width:76}} type="number" value={item.tax_rate} onChange={(e)=>updateItem(item.id,"tax_rate",Number(e.target.value))}/></td><td><input className="input" style={{width:76}} type="number" value={item.discount} onChange={(e)=>updateItem(item.id,"discount",Number(e.target.value))}/></td><td className="font-medium">{money(item.quantity*item.unit_price*(1-item.discount/100)*(1+item.tax_rate/100))}</td><td><button className="icon-btn w-8 h-8 text-[#d92d20]" onClick={()=>setDraft(current=>({...current,items:current.items.filter(row=>row.id!==item.id)}))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div><button className="btn mt-3" onClick={()=>setDraft(current=>({...current,items:[...current.items,blankItem()]}))}><Plus size={16}/>Add Item</button></FormCard>
      <FormCard title="4. Payment"><div className="grid sm:grid-cols-3 gap-3"><PaymentChoice label="Bank transfer" active={draft.payment_method==="bank"} onClick={()=>chooseMethod("bank")}/><PaymentChoice label="Cash" active={draft.payment_method==="cash"} disabled={!cashAllowed(totals.total)} onClick={()=>chooseMethod("cash")}/><PaymentChoice label="Card" active={draft.payment_method==="card"} onClick={()=>chooseMethod("card")}/></div>{draft.payment_method==="cash"&&<div className="mt-4 grid sm:grid-cols-2 gap-4"><label className="field"><span className="flex">Amount paid (€)<button className="ml-auto text-[#004ffe]" onClick={()=>update("amount_received",Number(totals.total.toFixed(2)))}>Exact amount</button></span><input className="input" type="number" step=".01" value={draft.amount_received} onChange={(e)=>update("amount_received",Number(e.target.value))}/></label><div className="field"><span>Change</span><strong className="input bg-[#f7f9fc] text-[#004ffe]">{money(payment.change)}</strong></div></div>}<p className="text-[11px] muted mt-3">Cash is available for invoices below €300.</p></FormCard>
      <FormCard title="5. Invoice Template"><div className="grid sm:grid-cols-2 gap-3"><button type="button" className={`btn text-left ${template==="corporate"?"border-[#004ffe] bg-[#edf4ff] text-[#004ffe]":""}`} onClick={()=>{setTemplate("corporate");setTemplateConfig(current=>({...current,style:"corporate",pageSize:"A4"}))}}><b className="block">Corporate</b><span className="text-[11px] muted">A4 professional invoice</span></button><button type="button" className={`btn text-left ${template==="thermal"?"border-[#004ffe] bg-[#edf4ff] text-[#004ffe]":""}`} onClick={()=>{setTemplate("thermal");setTemplateConfig(current=>({...current,style:"thermal",pageSize:"Receipt"}))}}><b className="block">Thermal Receipt</b><span className="text-[11px] muted">Compact 50 mm receipt</span></button></div></FormCard>
      <FormCard title="6. Notes"><textarea className="textarea" value={draft.notes} onChange={(e)=>update("notes",e.target.value)} placeholder="Add payment terms or notes…"/></FormCard>
      <div className="card p-5 ml-auto w-full sm:w-80"><SummaryLine label="Subtotal" value={totals.subtotal}/><SummaryLine label="Tax" value={totals.tax}/><SummaryLine label="Discount" value={-totals.discount}/><div className="border-t mt-3 pt-3 flex font-semibold text-lg"><span>Total</span><span className="ml-auto text-[#004ffe]">{money(totals.total)}</span></div></div>
    </div><aside className={`min-w-0 ${previewMode?"max-w-[840px] mx-auto w-full":"xl:sticky xl:top-20 self-start"}`}><div className="card p-3 sm:p-4 bg-[#f1f4f8]"><div className="flex items-center mb-3"><strong className="text-xs">Invoice Preview ({template==="thermal"?"50 mm":"A4"})</strong><span className="ml-auto text-[10px] text-[#12b76a]">● Live</span></div><div className="overflow-auto"><InvoiceDocument draft={draft} client={client} company={company} template={template} config={templateConfig}/></div><div className="mt-3 flex flex-wrap gap-2"><button className="btn flex-1" onClick={()=>print(template==="thermal")}>{template==="thermal"?"Print Receipt":"Print A4"}</button><button className="btn" onClick={download}><FileDown size={16}/>PDF</button></div></div></aside></div>
  </div>;
}
function FormCard({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-4"><h2 className="font-semibold mb-4">{title}</h2>{children}</section>;}function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="field"><span>{label}</span><input className="input" type={type} value={value} onChange={(e)=>onChange(e.target.value)}/></label>;}function PaymentChoice({label,active,disabled,onClick}:{label:string;active:boolean;disabled?:boolean;onClick:()=>void}){return <button disabled={disabled} className={`btn ${active?"border-[#004ffe] bg-[#edf4ff] text-[#004ffe]":""}`} onClick={onClick}>{label}</button>;}function SummaryLine({label,value}:{label:string;value:number}){return <div className="flex py-1.5 text-xs"><span className="muted">{label}</span><span className={`ml-auto ${value<0?"text-[#d92d20]":""}`}>{money(value)}</span></div>;}
