"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Filter, MoreVertical, Plus, Search, TrendingUp } from "lucide-react";
import { useBusinessData } from "@/hooks/use-business-data";
import type { InvoiceRow } from "@/lib/models";
import { money, shortDate, statusClass } from "@/lib/format";

const tabs = ["all","draft","sent","paid","partial","overdue"] as const;

export function InvoiceList({ type = "invoice" }: { type?: "invoice" | "offer" }) {
  const router = useRouter();
  const { data: fetched, loading, error } = useBusinessData<InvoiceRow>("invoices", "*, client:clients(name)");
  const source = fetched.filter((row) => type === "invoice" ? row.type !== "offer" : row.type === "offer");
  const [active, setActive] = useState<(typeof tabs)[number]>("all"); const [invoiceType, setInvoiceType] = useState("all"); const [query, setQuery] = useState(""); const [filtersOpen, setFiltersOpen] = useState(false); const [page, setPage] = useState(1);
  const [from,setFrom]=useState("");const [to,setTo]=useState("");const [minimum,setMinimum]=useState("");
  const filtered = useMemo(() => source.filter((invoice) => (active === "all" || invoice.status === active) && (invoiceType === "all" || (invoice.type || "invoice") === invoiceType) && `${invoice.invoice_number} ${invoice.client?.name}`.toLowerCase().includes(query.toLowerCase())&&(!from||invoice.issue_date>=from)&&(!to||invoice.issue_date<=to)&&(!minimum||Number(invoice.total_amount)>=Number(minimum))), [source,active,invoiceType,query,from,to,minimum]);
  const perPage = 8; const pages = Math.max(1,Math.ceil(filtered.length/perPage)); const rows = filtered.slice((page-1)*perPage,page*perPage);
  const total = source.reduce((sum,row)=>sum+Number(row.total_amount),0); const paid = source.filter(r=>r.status==="paid").reduce((sum,row)=>sum+Number(row.total_amount),0); const overdue = source.filter(r=>r.status==="overdue").reduce((sum,row)=>sum+Number(row.total_amount),0);
  function exportCsv(){const lines=[["Number","Customer","Issue date","Due date","Amount","Status"],...filtered.map(row=>[row.invoice_number,row.client?.name||"",row.issue_date,row.due_date||"",row.total_amount,row.status])];const blob=new Blob([lines.map(line=>line.map(value=>`"${String(value).replaceAll("\"","\"\"")}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`operix-${type}s-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
  return <div className="p-4 lg:p-6 max-w-[1700px] mx-auto">
    <div className="flex items-center justify-between gap-4"><h1 className="page-title">{type === "invoice" ? "Invoices" : "Quotes"}</h1><div className="flex gap-2">{type === "offer" && source[0] ? <Link href={`/invoices/new?convert=${source[0].id}`} className="btn hidden sm:inline-flex">Convert latest quote</Link> : null}<Link href={`/invoices/new${type === "offer" ? "?type=offer" : ""}`} className="btn btn-primary"><Plus size={17}/>New {type === "invoice" ? "Invoice" : "Quote"}</Link></div></div>
    <div className="mt-5 flex flex-wrap items-center gap-3"><div className="card flex min-w-0 max-w-full overflow-x-auto p-1">{tabs.map((tab)=><button key={tab} onClick={()=>{setActive(tab);setPage(1)}} className={`capitalize min-w-20 px-4 h-10 rounded-md text-xs ${active===tab ? "text-[#004ffe] bg-[#edf4ff] font-medium" : "muted hover:text-[#111827]"}`}>{tab}</button>)}</div><select aria-label="Filter by invoice type" className="select h-12 w-full sm:w-auto" value={invoiceType} onChange={event=>{setInvoiceType(event.target.value);setPage(1)}}><option value="all">All types</option><option value="invoice">Invoices</option><option value="offer">Quotes</option><option value="proforma">Proforma</option><option value="order">Orders</option></select><label className="relative min-w-[220px] flex-1 sm:min-w-[250px]"><Search size={18} className="absolute left-3 top-3 text-[#98a2b3]"/><input value={query} onChange={(e)=>{setQuery(e.target.value);setPage(1)}} className="input pl-10" placeholder={`Search ${type === "invoice" ? "invoices" : "quotes"}`}/></label><button className="btn shrink-0 justify-center whitespace-nowrap" onClick={()=>setFiltersOpen(!filtersOpen)}><Filter size={17}/>Filters</button><button className="btn shrink-0 justify-center whitespace-nowrap" onClick={exportCsv}><Download size={17}/>Export</button></div>
    {filtersOpen && <div className="card mt-3 p-4 grid sm:grid-cols-4 gap-3"><label className="field"><span>From</span><input className="input" type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1)}}/></label><label className="field"><span>To</span><input className="input" type="date" value={to} onChange={event=>{setTo(event.target.value);setPage(1)}}/></label><label className="field"><span>Minimum amount</span><input className="input" type="number" placeholder="€0.00" value={minimum} onChange={event=>{setMinimum(event.target.value);setPage(1)}}/></label><div className="flex items-end"><button className="btn w-full" onClick={()=>{setFrom("");setTo("");setMinimum("");setPage(1)}}>Clear filters</button></div></div>}
    <section className="card mt-4 grid sm:grid-cols-2 xl:grid-cols-4 divide-y sm:divide-y-0 sm:divide-x divide-[#e4e9f0]">
      <Summary label={`Total ${type === "invoice" ? "Invoiced" : "Quoted"}`} value={money(total)} note="+12.5%" icon={TrendingUp}/><Summary label="Paid" value={money(paid)} note="+15.7%" icon={CheckCircle2} green/><Summary label="Outstanding" value={money(total-paid)} note={`${source.filter(i=>i.status!=="paid").length} documents`} icon={Clock3} orange/><Summary label="Overdue" value={money(overdue)} note={`${source.filter(i=>i.status==="overdue").length} documents`} icon={AlertCircle} red/>
    </section>
    <section className="card mt-4 overflow-hidden">
      {error && <div className="m-4 p-3 text-xs rounded bg-[#fff3f2] text-[#d92d20]">{error}</div>}
      <div className="table-wrap"><table className="data-table"><thead><tr><th>{type === "invoice" ? "Invoice #" : "Quote #"}</th><th>Customer</th><th>Issue Date</th><th>Due Date</th><th>Amount</th><th>Status</th><th className="w-20">Actions</th></tr></thead><tbody>{loading ? Array.from({length:6}).map((_,i)=><tr key={i}>{Array.from({length:7}).map((__,j)=><td key={j}><div className="skeleton h-4 rounded"/></td>)}</tr>) : rows.length ? rows.map((invoice)=><tr key={invoice.id} className="cursor-pointer hover:bg-[#fbfcff]" tabIndex={0} onClick={() => router.push(`/invoices/preview/${encodeURIComponent(invoice.invoice_number)}`)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); router.push(`/invoices/preview/${encodeURIComponent(invoice.invoice_number)}`); } }}><td><Link className="text-[#004ffe] font-medium" href={`/invoices/preview/${encodeURIComponent(invoice.invoice_number)}`} onClick={(event) => event.stopPropagation()}>{invoice.invoice_number}</Link></td><td>{invoice.client?.name || "—"}</td><td>{shortDate(invoice.issue_date)}</td><td className={invoice.status==="overdue" ? "text-[#ef4444]" : ""}>{shortDate(invoice.due_date)}</td><td className="font-medium">{money(invoice.total_amount)}</td><td><span className={statusClass(invoice.status)}>{invoice.status}</span></td><td><details className="relative" onClick={(event) => event.stopPropagation()}><summary className="list-none icon-btn border-0 w-8 h-8"><MoreVertical size={17}/></summary><div className="absolute right-0 z-10 w-40 card shadow-xl p-1"><Link href={`/invoices/preview/${encodeURIComponent(invoice.invoice_number)}`} className="block p-2 rounded hover:bg-[#f7f9fc] text-xs">View & download</Link><Link href={`/invoices/new?edit=${invoice.id}`} className="block p-2 rounded hover:bg-[#f7f9fc] text-xs">Edit</Link></div></details></td></tr>) : <tr><td colSpan={7} className="text-center muted py-14">No matching documents found.</td></tr>}</tbody></table></div>
      <footer className="px-5 py-4 flex items-center border-t border-[#e4e9f0] text-xs muted"><span>Showing {filtered.length ? (page-1)*perPage+1 : 0}–{Math.min(page*perPage,filtered.length)} of {filtered.length} {type === "invoice" ? "invoices" : "quotes"}</span><div className="ml-auto flex items-center gap-2"><button className="icon-btn w-8 h-8" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button><span className="w-8 h-8 rounded bg-[#004ffe] text-white grid place-items-center">{page}</span><button className="icon-btn w-8 h-8" disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button></div></footer>
    </section>
  </div>;
}

function Summary({label,value,note,icon:Icon,green,orange,red}:{label:string;value:string;note:string;icon:typeof TrendingUp;green?:boolean;orange?:boolean;red?:boolean}) { const tone=green?"text-[#12b76a] bg-[#e9f9f0]":orange?"text-[#f59e0b] bg-[#fff4e5]":red?"text-[#ef4444] bg-[#fff0ef]":"text-[#004ffe] bg-[#edf4ff]"; return <div className="p-5 flex items-center gap-4"><span className={`w-10 h-10 rounded-md grid place-items-center ${tone}`}><Icon size={20}/></span><div><span className="text-[11px] muted">{label}</span><strong className="block text-lg mt-1">{value}</strong><small className={red?"text-[#ef4444]":green?"text-[#12b76a]":"muted"}>{note}</small></div></div>; }
