"use client";

import { useEffect, useState } from "react";
import { Copy, ExternalLink, Plus, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useWorkspace } from "@/hooks/use-workspace";
import { useBusinessData } from "@/hooks/use-business-data";
import type { ClientRow } from "@/lib/models";

type PortalToken = { id:string; token:string; client_id:string; expires_at?:string|null; last_used_at?:string|null; client?:{name:string}|null };
export function PortalLinksView(){
  const workspace=useWorkspace(); const clients=useBusinessData<ClientRow>("clients"); const [links,setLinks]=useState<PortalToken[]>([]); const [clientId,setClientId]=useState(""); const [expires,setExpires]=useState(""); const [message,setMessage]=useState("");
  const load=async()=>{const supabase=createClient();if(!supabase||!workspace.user)return;const {data,error}=await supabase.from("customer_portal_tokens").select("*, client:clients(name)").eq("user_id",workspace.user.id).order("created_at",{ascending:false});if(error)setMessage(error.message);else setLinks((data||[]) as PortalToken[]);};
  useEffect(()=>{void load();},[workspace.user]);
  async function createLink(){const supabase=createClient();if(!supabase||!workspace.user){setMessage("Your session has expired.");return;}if(!clientId){setMessage("Choose a customer first.");return;}const {data,error}=await supabase.from("customer_portal_tokens").insert({user_id:workspace.user.id,company_id:workspace.companyId,client_id:clientId,expires_at:expires||null}).select("*, client:clients(name)").single();if(error)setMessage(error.message);else{setLinks(current=>[data as PortalToken,...current]);setClientId("");setExpires("");setMessage("Portal link created.");}}
  async function remove(id:string){const supabase=createClient();if(supabase)await supabase.from("customer_portal_tokens").delete().eq("id",id);setLinks(current=>current.filter(link=>link.id!==id));}
  function url(token:string){return `${window.location.origin}/portal/${token}`;}
  return <div className="mx-auto max-w-[1400px] p-4 lg:p-6"><header className="flex flex-wrap items-end gap-4"><div><h1 className="page-title">Customer Portal</h1><p className="muted mt-1.5 text-xs">Share secure, read-only invoice views with customers.</p></div></header><section className="card mt-5 p-5"><h2 className="font-semibold">Create a portal link</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><select className="select" value={clientId} onChange={event=>setClientId(event.target.value)}><option value="">Choose customer</option>{clients.data.map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select><input className="input" type="date" value={expires} onChange={event=>setExpires(event.target.value)} aria-label="Expiry date"/><button className="btn btn-primary" onClick={createLink}><Plus size={16}/>Create link</button></div>{message&&<p className="mt-3 text-xs text-[#004ffe]">{message}</p>}</section><section className="card mt-5 overflow-hidden"><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Portal URL</th><th>Expires</th><th>Last opened</th><th>Actions</th></tr></thead><tbody>{links.length?links.map(link=><tr key={link.id}><td className="font-medium">{link.client?.name||"Customer"}</td><td><div className="flex max-w-[420px] items-center gap-2"><code className="truncate text-[11px]">{url(link.token)}</code><button className="icon-btn h-8 w-8" onClick={()=>navigator.clipboard.writeText(url(link.token))} aria-label="Copy portal URL"><Copy size={14}/></button><a className="icon-btn h-8 w-8" href={url(link.token)} target="_blank" rel="noreferrer" aria-label="Open portal"><ExternalLink size={14}/></a></div></td><td>{link.expires_at?new Date(link.expires_at).toLocaleDateString():"Never"}</td><td>{link.last_used_at?new Date(link.last_used_at).toLocaleDateString():"Not opened"}</td><td><button className="icon-btn h-8 w-8 text-[#d92d20]" onClick={()=>remove(link.id)} aria-label="Delete portal link"><Trash2 size={14}/></button></td></tr>):<tr><td colSpan={5} className="muted py-12 text-center">No portal links yet.</td></tr>}</tbody></table></div></section></div>;
}
