create type public.userrole as enum (
  'employee',
  'team_leader',
  'manager',
  'admin'
);

create type public.resourcetype as enum (
  'desk',
  'room'
);

create type public.reservationstatus as enum (
  'active',
  'cancelled',
  'resource_removed'
);

create table public.users (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  hashed_password varchar(255) not null,
  role public.userrole not null default 'employee',
  full_name varchar(255) not null,
  job_title varchar(150),
  team_name varchar(150),
  profile_image_path varchar(255),
  team_leader_id integer references public.users(id),
  password_reset_token_hash varchar(255),
  password_reset_expires_at timestamptz,
  must_change_password boolean not null default false
);

create table public.resources (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  type public.resourcetype not null,
  building varchar(120) not null default 'HQ - Prishtina',
  floor varchar(50) not null,
  zone varchar(100) not null,
  floor_plan_x double precision,
  floor_plan_y double precision,
  capacity integer not null default 1,
  amenities text,
  is_active boolean not null default true,
  desk_type varchar(100)
);

create table public.reservations (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id),
  resource_id integer not null references public.resources(id),
  date date not null,
  start_time time,
  end_time time,
  status public.reservationstatus not null default 'active'
);

create table public.floor_plans (
  id integer generated by default as identity primary key,
  name varchar(150),
  building varchar(100) not null default 'HQ',
  floor varchar(50) not null unique,
  image_path varchar(500) not null
);

create table public.favorites (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  resource_id integer not null references public.resources(id) on delete cascade,
  constraint uq_favorites_user_resource unique (user_id, resource_id)
);

create table public.audit_logs (
  id integer generated by default as identity primary key,
  actor_id integer not null references public.users(id),
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id integer,
  details text,
  created_at timestamptz not null default now()
);

create index ix_users_email on public.users (email);
create index ix_users_role on public.users (role);
create index ix_users_team_name on public.users (team_name);
create index ix_users_team_leader_id on public.users (team_leader_id);
create index ix_users_password_reset_token_hash on public.users (password_reset_token_hash)
where password_reset_token_hash is not null;

create index ix_resources_active_type on public.resources (is_active, type);
create index ix_resources_floor_zone on public.resources (floor, zone);
create index ix_resources_floor_name on public.resources (floor, name);
create index ix_resources_zone on public.resources (zone);

create index ix_reservations_user_id on public.reservations (user_id);
create index ix_reservations_resource_id on public.reservations (resource_id);
create index ix_reservations_date on public.reservations (date);
create index ix_reservations_status on public.reservations (status);
create index ix_reservations_user_date on public.reservations (user_id, date);
create index ix_reservations_resource_date_status on public.reservations (resource_id, date, status);

create index ix_floor_plans_floor on public.floor_plans (floor);

create index ix_favorites_user_id on public.favorites (user_id);
create index ix_favorites_resource_id on public.favorites (resource_id);

create index ix_audit_logs_actor_id on public.audit_logs (actor_id);
create index ix_audit_logs_created_at on public.audit_logs (created_at desc);
create index ix_audit_logs_entity on public.audit_logs (entity_type, entity_id);

alter table public.users enable row level security;
alter table public.resources enable row level security;
alter table public.reservations enable row level security;
alter table public.floor_plans enable row level security;
alter table public.favorites enable row level security;
alter table public.audit_logs enable row level security;

-- This app currently accesses Supabase through the FastAPI backend using the
-- Postgres connection string. Do not add broad anon/authenticated policies
-- unless you intentionally move reads or writes to the browser client.
